using System;
using NetProtocol.Packet.C2G;
using NetProtocol.Packet.G2C;

namespace NetProtocol.Packet.Trade
{
    public class TradePacketMeta : IPacketMeta
    {
        public int StartId => 29000;

        public Type[] Types => new[]
        {
            typeof(TradeCronAverageBalanceReq),
            typeof(TradeCronBalanceReq),
            typeof(TradeCronBuyReq),
            typeof(TradeCronInfoReq),
            typeof(TradeCronListReq),
            typeof(TradeCronPreviousDayBalanceReq),
            typeof(TradeCronSellReq),
            typeof(TradeCronWeeklyBalanceReq),
            typeof(TradeCronAverageBalanceRes),
            typeof(TradeCronBalanceRes),
            typeof(TradeCronBuyRes),
            typeof(TradeCronInfoRes),
            typeof(TradeCronListRes),
            typeof(TradeCronPreviousDayBalanceRes),
            typeof(TradeCronSellRes),
            typeof(TradeCronWeeklyBalanceRes),
            typeof(TradePersonalListNoti),
            typeof(TradePersonalRequestReq),
            typeof(TradePersonalRequestRes),
            typeof(TradePersonalUpdateNoti),
            typeof(TradePersonalAddNoti),
            typeof(TradePersonalDeleteNoti),
            typeof(TradePersonalAcceptReq),
            typeof(TradePersonalAcceptRes),
            typeof(TradePersonalRefuseReq),
            typeof(TradePersonalRefuseRes),
            typeof(TradePersonalCancelReq),
            typeof(TradePersonalCancelRes),
            typeof(TradePersonalWithdrawReq),
            typeof(TradePersonalWithdrawRes),
            typeof(TradePersonalFinishReq),
            typeof(TradePersonalFinishRes),
            typeof(TradePersonalHistoryReq),
            typeof(TradePersonalHistoryRes),
            typeof(TradeCronMyListReq),
            typeof(TradeCronMyListRes),
            typeof(TradeCronSettleReq),
            typeof(TradeCronSettleRes),
            typeof(TradeCronTradesReq),
            typeof(TradeCronTradesRes),
            typeof(TradeCronTimeToNextChangeBalanceReq),
            typeof(TradeCronTimeToNextChangeBalanceRes),
            typeof(TradeCronCancelReq),
            typeof(TradeCronCancelRes),
            typeof(TradeCronReclaimExpiredReq),
            typeof(TradeCronReclaimExpiredRes),
            typeof(TradeCronRemainingCanceledPenaltyTimeReq),
            typeof(TradeCronRemainingCanceledPenaltyTimeRes),
            typeof(TradeItemSellListNoti),
            typeof(TradeItemUpdateNoti),
            typeof(TradeItemDeleteNoti),
            typeof(TradeItemRegistReq),
            typeof(TradeItemRegistRes),
            typeof(TradeItemCancelReq),
            typeof(TradeItemCancelRes),
            typeof(TradeItemBuyReq),
            typeof(TradeItemBuyRes),
            typeof(TradeItemWithdrawReq),
            typeof(TradeItemWithdrawRes),
            typeof(TradeItemFinishReq),
            typeof(TradeItemFinishRes),
            typeof(TradeItemHistoryReq),
            typeof(TradeItemHistoryRes),
            typeof(TradeItemSearchCategoryReq),
            typeof(TradeItemSearchCategoryRes),
            typeof(TradeItemSearchItemIndexReq),
            typeof(TradeItemSearchItemIndexRes),
            typeof(TradeItemSearchListNoti),
            typeof(TradeItemBookmarkAddReq),
            typeof(TradeItemBookmarkAddRes),
            typeof(TradeItemBookmarkDeleteReq),
            typeof(TradeItemBookmarkDeleteRes),
            typeof(TradeItemBookmarkListNoti),
        };
    }
}