using System;
using NetProtocol.Packet.C2G;
using NetProtocol.Packet.G2C;

namespace NetProtocol.Packet.Guilds
{
    public class GuildsPacketMeta : IPacketMeta
    {
        public int StartId => 11000;

        public Type[] Types => new[]
        {
            typeof(GuildAdminBuffActiveReq),
            typeof(GuildAdminBuffBuyReq),
            typeof(GuildAdminInfoReq),
            typeof(GuildAdminLevelUpReq),
            typeof(GuildAdminMasterChangeReq),
            typeof(GuildAdminMemberBanishReq),
            typeof(GuildAdminMemberUpdateReq),
            typeof(GuildAdminUpdateBaseReq),
            typeof(GuildAdminUpdateIntroReq),
            typeof(GuildAdminUpdateNoticeReq),
            typeof(GuildAdminUpdateTendencyReq),
            typeof(GuildAdminUpdateTypeReq),
            typeof(GuildAttendReq),
            typeof(GuildBuffInfoReq),
            typeof(GuildCreateReq),
            typeof(GuildDeleteReq),
            typeof(GuildDonateReq),
            typeof(GuildDonationByCronV2Req),
            typeof(GuildFindReq),
            typeof(GuildHistroyReq),
            typeof(GuildInfoCallReq),
            typeof(GuildInfoReq),
            typeof(GuildJoinRequestConfirmReq),
            typeof(GuildJoinRequestListReq),
            typeof(GuildLeaveReq),
            typeof(GuildLiveInviteConfirmReq),
            typeof(GuildLiveInviteReq),
            typeof(GuildMemberInfoReq),
            typeof(GuildSignRequestCancelReq),
            typeof(GuildSignRequestListReq),
            typeof(GuildSignRequestReq),
            typeof(GuildVoteInfoReq),
            typeof(GuildVoteMasterImpeachReq),
            typeof(GuildVoteReq),
            typeof(GuildWaitingMemberListV2Req),
            typeof(GuildWarehouseChangeSizeV2Req),
            typeof(GuildWarehouseInfoV2Req),
            typeof(GuildWarehouseItemMoveV2Req),
            typeof(GuildWarehouseWalletMoveV2Req),
            typeof(GuildAdminBuffActiveRes),
            typeof(GuildAdminBuffBuyRes),
            typeof(GuildAdminInfoRes),
            typeof(GuildAdminMasterChangeNoti),
            typeof(GuildAdminMasterChangeRes),
            typeof(GuildAdminMemberBanishNoti),
            typeof(GuildAdminMemberBanishRes),
            typeof(GuildAdminMemberUpdateNoti),
            typeof(GuildAdminMemberUpdateRes),
            typeof(GuildAdminUpdateBaseNoti),
            typeof(GuildAdminUpdateBaseRes),
            typeof(GuildAdminUpdateIntroNoti),
            typeof(GuildAdminUpdateIntroRes),
            typeof(GuildAdminUpdateNoticeNoti),
            typeof(GuildAdminUpdateNoticeRes),
            typeof(GuildAdminUpdateTendencyNoti),
            typeof(GuildAdminUpdateTendencyRes),
            typeof(GuildAdminUpdateTypeNoti),
            typeof(GuildAdminUpdateTypeRes),
            typeof(GuildAttendRes),
            typeof(GuildBaseNoti),
            typeof(GuildBuffInfoRes),
            typeof(GuildBuffNoti),
            typeof(GuildCreateRes),
            typeof(GuildDeleteRes),
            typeof(GuildDonateRes),
            typeof(GuildDonationByCronV2Res),
            typeof(GuildFindRes),
            typeof(GuildHistoryNoti),
            typeof(GuildHistoryRes),
            typeof(GuildInfoCallRes),
            typeof(GuildInfoRes),
            typeof(GuildJoinRequestConfirmNoti),
            typeof(GuildJoinRequestConfirmRes),
            typeof(GuildJoinRequestListRes),
            typeof(GuildLeaveNoti),
            typeof(GuildLeaveRes),
            typeof(GuildLiveInviteConfirmNoti),
            typeof(GuildLiveInviteConfirmRes),
            typeof(GuildLiveInviteNoti),
            typeof(GuildLiveInviteRes),
            typeof(GuildMemberInfoRes),
            typeof(GuildMemberNoti),
            typeof(GuildMemberStateV2Noti),
            typeof(GuildMemberUpdateNoti),
            typeof(GuildPointNoti),
            typeof(GuildSignRequestCancelRes),
            typeof(GuildSignRequestListRes),
            typeof(GuildSignRequestRes),
            typeof(GuildUpdateCrestNoti),
            typeof(GuildUpdateCurrencyV2Noti),
            typeof(GuildVoteInfoRes),
            typeof(GuildVoteMasterImpeachRes),
            typeof(GuildVoteNoti),
            typeof(GuildVoteRes),
            typeof(GuildWarehouseChangeSizeV2Res),
            typeof(GuildWarehouseInfoV2Res),
            typeof(GuildWarehouseItemMoveV2Res),
            typeof(GuildWarehouseWalletMoveV2Res),
            typeof(GuildRubyNoti),
            typeof(GuildCronNoti),
            
            typeof(GuildTerritoryInfoReq),
            typeof(GuildTerritoryInfoRes),
            typeof(GuildTerritorySetReq),
            typeof(GuildTerritorySetRes),
            typeof(WorldTerritoryOverviewReq),
            typeof(WorldTerritoryOverviewRes),
            
            typeof(WorldBossLastAttackNoti),
            
            
        };
    }
}