 





// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
            
using System.Collections.Generic; 
namespace NetProtocol.Packet.C2G
{
	public class Common
	{
		// Message ID that replies to each RMI method. 
			public const Nettention.Proud.RmiID PlayerSelectReq = (Nettention.Proud.RmiID)1001;
			public const Nettention.Proud.RmiID PlayerEnterStageFirstReq = (Nettention.Proud.RmiID)1002;
			public const Nettention.Proud.RmiID PlayerEnterStageSecondReq = (Nettention.Proud.RmiID)1003;
			public const Nettention.Proud.RmiID PlayerEnterStageThirdReq = (Nettention.Proud.RmiID)1004;
			public const Nettention.Proud.RmiID PlayerEnterStageFourthReq = (Nettention.Proud.RmiID)1005;
			public const Nettention.Proud.RmiID PlayerEnterStageFifthReq = (Nettention.Proud.RmiID)1006;
			public const Nettention.Proud.RmiID PlayerGameEnterReq = (Nettention.Proud.RmiID)1007;
			public const Nettention.Proud.RmiID AuthenticateBotCredentialReq = (Nettention.Proud.RmiID)1015;
			public const Nettention.Proud.RmiID DesignateBindStoneReq = (Nettention.Proud.RmiID)3001;
			public const Nettention.Proud.RmiID PortalByBindStoneReq = (Nettention.Proud.RmiID)3002;
			public const Nettention.Proud.RmiID PlayerBlackRosterGetPreferenceReq = (Nettention.Proud.RmiID)4001;
			public const Nettention.Proud.RmiID PlayerBlackRosterObservingReq = (Nettention.Proud.RmiID)4002;
			public const Nettention.Proud.RmiID PlayerBlackRosterProvocationReq = (Nettention.Proud.RmiID)4003;
			public const Nettention.Proud.RmiID PlayerBlackRosterRankReq = (Nettention.Proud.RmiID)4004;
			public const Nettention.Proud.RmiID PlayerBlackRosterRevengeReq = (Nettention.Proud.RmiID)4005;
			public const Nettention.Proud.RmiID PlayerBlackRosterSetPreferenceReq = (Nettention.Proud.RmiID)4006;
			public const Nettention.Proud.RmiID PlayerBlackRostersReq = (Nettention.Proud.RmiID)4007;
			public const Nettention.Proud.RmiID PlayerBlackRosterLastWeekRankReq = (Nettention.Proud.RmiID)4017;
			public const Nettention.Proud.RmiID CheatMessageV2Req = (Nettention.Proud.RmiID)6001;
			public const Nettention.Proud.RmiID AccountBlockPlayerAddReq = (Nettention.Proud.RmiID)7001;
			public const Nettention.Proud.RmiID AccountBlockPlayerDeleteReq = (Nettention.Proud.RmiID)7002;
			public const Nettention.Proud.RmiID AccountBlockPlayerReasonEditReq = (Nettention.Proud.RmiID)7003;
			public const Nettention.Proud.RmiID AccountBlockPlayersReq = (Nettention.Proud.RmiID)7004;
			public const Nettention.Proud.RmiID ChatMessageV2Req = (Nettention.Proud.RmiID)7005;
			public const Nettention.Proud.RmiID PlayerSearchV2Req = (Nettention.Proud.RmiID)7006;
			public const Nettention.Proud.RmiID LinkItemInfoReq = (Nettention.Proud.RmiID)7014;
			public const Nettention.Proud.RmiID CostumeCardBuildReq = (Nettention.Proud.RmiID)8001;
			public const Nettention.Proud.RmiID CostumeCardGachaReq = (Nettention.Proud.RmiID)8003;
			public const Nettention.Proud.RmiID CostumeCardInfoReq = (Nettention.Proud.RmiID)8005;
			public const Nettention.Proud.RmiID CostumeCardMixReq = (Nettention.Proud.RmiID)8007;
			public const Nettention.Proud.RmiID CostumeCollectReq = (Nettention.Proud.RmiID)8009;
			public const Nettention.Proud.RmiID CostumeEquipBodyReq = (Nettention.Proud.RmiID)8012;
			public const Nettention.Proud.RmiID CostumeEquipBodyShowReq = (Nettention.Proud.RmiID)8014;
			public const Nettention.Proud.RmiID CostumeEquipHeadReq = (Nettention.Proud.RmiID)8016;
			public const Nettention.Proud.RmiID CostumeEquipHeadShowReq = (Nettention.Proud.RmiID)8018;
			public const Nettention.Proud.RmiID CostumeInfoReq = (Nettention.Proud.RmiID)8020;
			public const Nettention.Proud.RmiID CostumeConfirmAcceptReq = (Nettention.Proud.RmiID)8022;
			public const Nettention.Proud.RmiID CostumeConfirmChangeReq = (Nettention.Proud.RmiID)8023;
			public const Nettention.Proud.RmiID CostumeConfirmInfoReq = (Nettention.Proud.RmiID)8024;
			public const Nettention.Proud.RmiID PortalEffectReq = (Nettention.Proud.RmiID)9001;
			public const Nettention.Proud.RmiID AttainmentDailyRewardV2Req = (Nettention.Proud.RmiID)10001;
			public const Nettention.Proud.RmiID AttainmentNormalRewardV2Req = (Nettention.Proud.RmiID)10002;
			public const Nettention.Proud.RmiID AttendanceRewardV2Req = (Nettention.Proud.RmiID)10003;
			public const Nettention.Proud.RmiID BossScheduleReq = (Nettention.Proud.RmiID)10004;
			public const Nettention.Proud.RmiID EventExchangeRewardV2Req = (Nettention.Proud.RmiID)10005;
			public const Nettention.Proud.RmiID GuildAdminBuffActiveReq = (Nettention.Proud.RmiID)11001;
			public const Nettention.Proud.RmiID GuildAdminBuffBuyReq = (Nettention.Proud.RmiID)11002;
			public const Nettention.Proud.RmiID GuildAdminInfoReq = (Nettention.Proud.RmiID)11003;
			public const Nettention.Proud.RmiID GuildAdminLevelUpReq = (Nettention.Proud.RmiID)11004;
			public const Nettention.Proud.RmiID GuildAdminMasterChangeReq = (Nettention.Proud.RmiID)11005;
			public const Nettention.Proud.RmiID GuildAdminMemberBanishReq = (Nettention.Proud.RmiID)11006;
			public const Nettention.Proud.RmiID GuildAdminMemberUpdateReq = (Nettention.Proud.RmiID)11007;
			public const Nettention.Proud.RmiID GuildAdminUpdateBaseReq = (Nettention.Proud.RmiID)11008;
			public const Nettention.Proud.RmiID GuildAdminUpdateIntroReq = (Nettention.Proud.RmiID)11009;
			public const Nettention.Proud.RmiID GuildAdminUpdateNoticeReq = (Nettention.Proud.RmiID)11010;
			public const Nettention.Proud.RmiID GuildAdminUpdateTendencyReq = (Nettention.Proud.RmiID)11011;
			public const Nettention.Proud.RmiID GuildAdminUpdateTypeReq = (Nettention.Proud.RmiID)11012;
			public const Nettention.Proud.RmiID GuildAttendReq = (Nettention.Proud.RmiID)11013;
			public const Nettention.Proud.RmiID GuildBuffInfoReq = (Nettention.Proud.RmiID)11014;
			public const Nettention.Proud.RmiID GuildCreateReq = (Nettention.Proud.RmiID)11015;
			public const Nettention.Proud.RmiID GuildDeleteReq = (Nettention.Proud.RmiID)11016;
			public const Nettention.Proud.RmiID GuildDonateReq = (Nettention.Proud.RmiID)11017;
			public const Nettention.Proud.RmiID GuildDonationByCronV2Req = (Nettention.Proud.RmiID)11018;
			public const Nettention.Proud.RmiID GuildFindReq = (Nettention.Proud.RmiID)11019;
			public const Nettention.Proud.RmiID GuildHistroyReq = (Nettention.Proud.RmiID)11020;
			public const Nettention.Proud.RmiID GuildInfoCallReq = (Nettention.Proud.RmiID)11021;
			public const Nettention.Proud.RmiID GuildInfoReq = (Nettention.Proud.RmiID)11022;
			public const Nettention.Proud.RmiID GuildJoinRequestConfirmReq = (Nettention.Proud.RmiID)11023;
			public const Nettention.Proud.RmiID GuildJoinRequestListReq = (Nettention.Proud.RmiID)11024;
			public const Nettention.Proud.RmiID GuildLeaveReq = (Nettention.Proud.RmiID)11025;
			public const Nettention.Proud.RmiID GuildLiveInviteConfirmReq = (Nettention.Proud.RmiID)11026;
			public const Nettention.Proud.RmiID GuildLiveInviteReq = (Nettention.Proud.RmiID)11027;
			public const Nettention.Proud.RmiID GuildMemberInfoReq = (Nettention.Proud.RmiID)11028;
			public const Nettention.Proud.RmiID GuildSignRequestCancelReq = (Nettention.Proud.RmiID)11029;
			public const Nettention.Proud.RmiID GuildSignRequestListReq = (Nettention.Proud.RmiID)11030;
			public const Nettention.Proud.RmiID GuildSignRequestReq = (Nettention.Proud.RmiID)11031;
			public const Nettention.Proud.RmiID GuildVoteInfoReq = (Nettention.Proud.RmiID)11032;
			public const Nettention.Proud.RmiID GuildVoteMasterImpeachReq = (Nettention.Proud.RmiID)11033;
			public const Nettention.Proud.RmiID GuildVoteReq = (Nettention.Proud.RmiID)11034;
			public const Nettention.Proud.RmiID GuildWaitingMemberListV2Req = (Nettention.Proud.RmiID)11035;
			public const Nettention.Proud.RmiID GuildWarehouseChangeSizeV2Req = (Nettention.Proud.RmiID)11036;
			public const Nettention.Proud.RmiID GuildWarehouseInfoV2Req = (Nettention.Proud.RmiID)11037;
			public const Nettention.Proud.RmiID GuildWarehouseItemMoveV2Req = (Nettention.Proud.RmiID)11038;
			public const Nettention.Proud.RmiID GuildWarehouseWalletMoveV2Req = (Nettention.Proud.RmiID)11039;
			public const Nettention.Proud.RmiID GuildTerritoryInfoReq = (Nettention.Proud.RmiID)11101;
			public const Nettention.Proud.RmiID GuildTerritorySetReq = (Nettention.Proud.RmiID)11103;
			public const Nettention.Proud.RmiID WorldTerritoryOverviewReq = (Nettention.Proud.RmiID)11105;
			public const Nettention.Proud.RmiID DungeonEnterV2Req = (Nettention.Proud.RmiID)12001;
			public const Nettention.Proud.RmiID DungeonGiveUpV2Req = (Nettention.Proud.RmiID)12002;
			public const Nettention.Proud.RmiID DungeonLeaveV2Req = (Nettention.Proud.RmiID)12003;
			public const Nettention.Proud.RmiID DungeonLoadingCompleteV2Req = (Nettention.Proud.RmiID)12004;
			public const Nettention.Proud.RmiID InteractStartReq = (Nettention.Proud.RmiID)13001;
			public const Nettention.Proud.RmiID InteractEndReq = (Nettention.Proud.RmiID)13003;
			public const Nettention.Proud.RmiID InteractCancelReq = (Nettention.Proud.RmiID)13005;
			public const Nettention.Proud.RmiID EquipmentVisibleV2Req = (Nettention.Proud.RmiID)14001;
			public const Nettention.Proud.RmiID InventoryChangeSizeV2Req = (Nettention.Proud.RmiID)14002;
			public const Nettention.Proud.RmiID ItemAddOptionV2Req = (Nettention.Proud.RmiID)14003;
			public const Nettention.Proud.RmiID ItemChangeOptionV2Req = (Nettention.Proud.RmiID)14004;
			public const Nettention.Proud.RmiID ItemCollectionBookmarksRegisterV2Req = (Nettention.Proud.RmiID)14005;
			public const Nettention.Proud.RmiID ItemCollectionBookmarksUnregisterV2Req = (Nettention.Proud.RmiID)14006;
			public const Nettention.Proud.RmiID ItemCollectionRegisterV2Req = (Nettention.Proud.RmiID)14007;
			public const Nettention.Proud.RmiID ItemCombineV2Req = (Nettention.Proud.RmiID)14008;
			public const Nettention.Proud.RmiID ItemDeleteV2Req = (Nettention.Proud.RmiID)14009;
			public const Nettention.Proud.RmiID ItemDisassembleV2Req = (Nettention.Proud.RmiID)14010;
			public const Nettention.Proud.RmiID ItemEnchantV2Req = (Nettention.Proud.RmiID)14011;
			public const Nettention.Proud.RmiID ItemEquipV2Req = (Nettention.Proud.RmiID)14012;
			public const Nettention.Proud.RmiID ItemIntensionV2Req = (Nettention.Proud.RmiID)14013;
			public const Nettention.Proud.RmiID ItemMixOptionV2Req = (Nettention.Proud.RmiID)14014;
			public const Nettention.Proud.RmiID ItemPackageUseV2Req = (Nettention.Proud.RmiID)14015;
			public const Nettention.Proud.RmiID ItemProductionV2Req = (Nettention.Proud.RmiID)14016;
			public const Nettention.Proud.RmiID ItemSelectUseV2Req = (Nettention.Proud.RmiID)14017;
			public const Nettention.Proud.RmiID ItemUpgradeV2Req = (Nettention.Proud.RmiID)14018;
			public const Nettention.Proud.RmiID ItemUseV2Req = (Nettention.Proud.RmiID)14019;
			public const Nettention.Proud.RmiID PkLootingItemV2Req = (Nettention.Proud.RmiID)14020;
			public const Nettention.Proud.RmiID PkLootingListV2Req = (Nettention.Proud.RmiID)14021;
			public const Nettention.Proud.RmiID WarehouseChangeSizeV2Req = (Nettention.Proud.RmiID)14022;
			public const Nettention.Proud.RmiID WarehouseInfoV2Req = (Nettention.Proud.RmiID)14023;
			public const Nettention.Proud.RmiID WarehouseItemMoveV2Req = (Nettention.Proud.RmiID)14024;
			public const Nettention.Proud.RmiID ItemSetLockReq = (Nettention.Proud.RmiID)14059;
			public const Nettention.Proud.RmiID ItemMarketPriceReq = (Nettention.Proud.RmiID)14061;
			public const Nettention.Proud.RmiID ItemInheritReq = (Nettention.Proud.RmiID)14063;
			public const Nettention.Proud.RmiID MailListV2Req = (Nettention.Proud.RmiID)15001;
			public const Nettention.Proud.RmiID MailReadAllV2Req = (Nettention.Proud.RmiID)15002;
			public const Nettention.Proud.RmiID MailReadV2Req = (Nettention.Proud.RmiID)15003;
			public const Nettention.Proud.RmiID MatchingApplyReq = (Nettention.Proud.RmiID)16001;
			public const Nettention.Proud.RmiID MatchingCancelReq = (Nettention.Proud.RmiID)16002;
			public const Nettention.Proud.RmiID MatchingReplyReq = (Nettention.Proud.RmiID)16003;
			public const Nettention.Proud.RmiID AuthenticatePlayerCredentialReq = (Nettention.Proud.RmiID)17001;
			public const Nettention.Proud.RmiID BroadCastContextReq = (Nettention.Proud.RmiID)17002;
			public const Nettention.Proud.RmiID CutSceneEndV2Req = (Nettention.Proud.RmiID)17003;
			public const Nettention.Proud.RmiID CutSceneStartV2Req = (Nettention.Proud.RmiID)17004;
			public const Nettention.Proud.RmiID LogOutReq = (Nettention.Proud.RmiID)17005;
			public const Nettention.Proud.RmiID PortalV2Req = (Nettention.Proud.RmiID)17006;
			public const Nettention.Proud.RmiID ReturnToLobbyReq = (Nettention.Proud.RmiID)17007;
			public const Nettention.Proud.RmiID ServerTimeV2Req = (Nettention.Proud.RmiID)17008;
			public const Nettention.Proud.RmiID TestPacketV2Req = (Nettention.Proud.RmiID)17009;
			public const Nettention.Proud.RmiID TriggerActivateV2Req = (Nettention.Proud.RmiID)17010;
			public const Nettention.Proud.RmiID UnionV2Req = (Nettention.Proud.RmiID)17011;
			public const Nettention.Proud.RmiID ZoneLoadingCompletedReq = (Nettention.Proud.RmiID)17012;
			public const Nettention.Proud.RmiID BossDamagedInfoReq = (Nettention.Proud.RmiID)17042;
			public const Nettention.Proud.RmiID PartyChangeLootingReq = (Nettention.Proud.RmiID)18001;
			public const Nettention.Proud.RmiID PartyCreateReq = (Nettention.Proud.RmiID)18002;
			public const Nettention.Proud.RmiID PartyDisbandReq = (Nettention.Proud.RmiID)18003;
			public const Nettention.Proud.RmiID PartyDungeonEntranceInquiryReq = (Nettention.Proud.RmiID)18004;
			public const Nettention.Proud.RmiID PartyEnterDungeonReplyReq = (Nettention.Proud.RmiID)18005;
			public const Nettention.Proud.RmiID PartyEnterDungeonReq = (Nettention.Proud.RmiID)18006;
			public const Nettention.Proud.RmiID PartyInfoReq = (Nettention.Proud.RmiID)18007;
			public const Nettention.Proud.RmiID PartyInviteReplyReq = (Nettention.Proud.RmiID)18008;
			public const Nettention.Proud.RmiID PartyInviteReq = (Nettention.Proud.RmiID)18009;
			public const Nettention.Proud.RmiID PartyLeaderChangeReq = (Nettention.Proud.RmiID)18010;
			public const Nettention.Proud.RmiID PartyLeaveReq = (Nettention.Proud.RmiID)18011;
			public const Nettention.Proud.RmiID PartyMemberKickReq = (Nettention.Proud.RmiID)18012;
			public const Nettention.Proud.RmiID PartySuggestionPlayersReq = (Nettention.Proud.RmiID)18013;
			public const Nettention.Proud.RmiID PartyEnterDungeonCanceledReq = (Nettention.Proud.RmiID)18041;
			public const Nettention.Proud.RmiID PetCollectInfoV2Req = (Nettention.Proud.RmiID)19001;
			public const Nettention.Proud.RmiID PetEquipOffV2Req = (Nettention.Proud.RmiID)19002;
			public const Nettention.Proud.RmiID PetEquipV2Req = (Nettention.Proud.RmiID)19003;
			public const Nettention.Proud.RmiID PetFeedUseV2Req = (Nettention.Proud.RmiID)19004;
			public const Nettention.Proud.RmiID PetGachaV2Req = (Nettention.Proud.RmiID)19005;
			public const Nettention.Proud.RmiID PetInfoV2Req = (Nettention.Proud.RmiID)19006;
			public const Nettention.Proud.RmiID PetMixV2Req = (Nettention.Proud.RmiID)19007;
			public const Nettention.Proud.RmiID PetUpgradeV2Req = (Nettention.Proud.RmiID)19008;
			public const Nettention.Proud.RmiID PetInActiveBuffReq = (Nettention.Proud.RmiID)19019;
			public const Nettention.Proud.RmiID PhaseFieldEndV2Req = (Nettention.Proud.RmiID)20001;
			public const Nettention.Proud.RmiID PhaseFieldStartV2Req = (Nettention.Proud.RmiID)20002;
			public const Nettention.Proud.RmiID PlayerDeleteReq = (Nettention.Proud.RmiID)21002;
			public const Nettention.Proud.RmiID PlayerGetMacroReq = (Nettention.Proud.RmiID)21003;
			public const Nettention.Proud.RmiID PlayerMapMoveV2Req = (Nettention.Proud.RmiID)21004;
			public const Nettention.Proud.RmiID PlayerMoveV2Req = (Nettention.Proud.RmiID)21005;
			public const Nettention.Proud.RmiID PlayerMoveZoneV2Req = (Nettention.Proud.RmiID)21006;
			public const Nettention.Proud.RmiID PlayerResurrectionV2Req = (Nettention.Proud.RmiID)21007;
			public const Nettention.Proud.RmiID PlayerSetMacroReq = (Nettention.Proud.RmiID)21008;
			public const Nettention.Proud.RmiID PlayerSlotChangeV2Req = (Nettention.Proud.RmiID)21009;
			public const Nettention.Proud.RmiID PlayerStatPointChangeV2Req = (Nettention.Proud.RmiID)21010;
			public const Nettention.Proud.RmiID PlayerStatPointInitV2Req = (Nettention.Proud.RmiID)21011;
			public const Nettention.Proud.RmiID PlayerStatV2Req = (Nettention.Proud.RmiID)21012;
			public const Nettention.Proud.RmiID PlayerDeathInfoReq = (Nettention.Proud.RmiID)21035;
			public const Nettention.Proud.RmiID RecoverPlayerExpReq = (Nettention.Proud.RmiID)21037;
			public const Nettention.Proud.RmiID PlayerClassUpV2Req = (Nettention.Proud.RmiID)21040;
			public const Nettention.Proud.RmiID QuickslotSetReq = (Nettention.Proud.RmiID)21042;
			public const Nettention.Proud.RmiID PlayerExpRecoveryPopupReq = (Nettention.Proud.RmiID)21048;
			public const Nettention.Proud.RmiID RTTPlayerMoveV2Req = (Nettention.Proud.RmiID)21050;
			public const Nettention.Proud.RmiID QuestAbandonV2Req = (Nettention.Proud.RmiID)22001;
			public const Nettention.Proud.RmiID QuestAcceptV2Req = (Nettention.Proud.RmiID)22002;
			public const Nettention.Proud.RmiID QuestCompleteV2Req = (Nettention.Proud.RmiID)22003;
			public const Nettention.Proud.RmiID QuestConditionCompleteV2Req = (Nettention.Proud.RmiID)22004;
			public const Nettention.Proud.RmiID QuestListV2Req = (Nettention.Proud.RmiID)22005;
			public const Nettention.Proud.RmiID QuestPortalV2Req = (Nettention.Proud.RmiID)22006;
			public const Nettention.Proud.RmiID QuestRegisterV2Req = (Nettention.Proud.RmiID)22007;
			public const Nettention.Proud.RmiID QuestRerollV2Req = (Nettention.Proud.RmiID)22008;
			public const Nettention.Proud.RmiID QuestRewardV2Req = (Nettention.Proud.RmiID)22009;
			public const Nettention.Proud.RmiID QuestTalkCompleteV2Req = (Nettention.Proud.RmiID)22010;
			public const Nettention.Proud.RmiID TutorialSkipV2Req = (Nettention.Proud.RmiID)22011;
			public const Nettention.Proud.RmiID GuildRelationReq = (Nettention.Proud.RmiID)23001;
			public const Nettention.Proud.RmiID PlayerRelationReq = (Nettention.Proud.RmiID)23002;
			public const Nettention.Proud.RmiID RideAttachDeleteV2Req = (Nettention.Proud.RmiID)24001;
			public const Nettention.Proud.RmiID RideAttachDisassembleV2Req = (Nettention.Proud.RmiID)24002;
			public const Nettention.Proud.RmiID RideAttachEquipOffV2Req = (Nettention.Proud.RmiID)24003;
			public const Nettention.Proud.RmiID RideAttachEquipV2Req = (Nettention.Proud.RmiID)24004;
			public const Nettention.Proud.RmiID RideAttachGachaV2Req = (Nettention.Proud.RmiID)24005;
			public const Nettention.Proud.RmiID RideAttachInvenExtendV2Req = (Nettention.Proud.RmiID)24006;
			public const Nettention.Proud.RmiID RideEquipOffV2Req = (Nettention.Proud.RmiID)24007;
			public const Nettention.Proud.RmiID RideEquipV2Req = (Nettention.Proud.RmiID)24008;
			public const Nettention.Proud.RmiID RideGachaV2Req = (Nettention.Proud.RmiID)24009;
			public const Nettention.Proud.RmiID RideMixV2Req = (Nettention.Proud.RmiID)24010;
			public const Nettention.Proud.RmiID RideSitOffV2Req = (Nettention.Proud.RmiID)24011;
			public const Nettention.Proud.RmiID RideSitV2Req = (Nettention.Proud.RmiID)24012;
			public const Nettention.Proud.RmiID BuyCashShopItemV2Req = (Nettention.Proud.RmiID)25001;
			public const Nettention.Proud.RmiID BuyGameShopItemV2Req = (Nettention.Proud.RmiID)25002;
			public const Nettention.Proud.RmiID GameShopSellItemV2Req = (Nettention.Proud.RmiID)25003;
			public const Nettention.Proud.RmiID ChangeSiegeModeV2Req = (Nettention.Proud.RmiID)26001;
			public const Nettention.Proud.RmiID ChoiceSiegeWarFactionV2Req = (Nettention.Proud.RmiID)26002;
			public const Nettention.Proud.RmiID GetSiegeWarInfoV2Req = (Nettention.Proud.RmiID)26003;
			public const Nettention.Proud.RmiID GetSiegeWarMatchInfoV2Req = (Nettention.Proud.RmiID)26004;
			public const Nettention.Proud.RmiID BuffListInfoV2Req = (Nettention.Proud.RmiID)27001;
			public const Nettention.Proud.RmiID SkillChangeAutoUseV2Req = (Nettention.Proud.RmiID)27002;
			public const Nettention.Proud.RmiID SkillChangePresetV2Req = (Nettention.Proud.RmiID)27003;
			public const Nettention.Proud.RmiID SkillEquipV2Req = (Nettention.Proud.RmiID)27004;
			public const Nettention.Proud.RmiID SkillHitV2Req = (Nettention.Proud.RmiID)27005;
			public const Nettention.Proud.RmiID SkillLearnV2Req = (Nettention.Proud.RmiID)27006;
			public const Nettention.Proud.RmiID SkillLevelUpV2Req = (Nettention.Proud.RmiID)27007;
			public const Nettention.Proud.RmiID SkillListInfoV2Req = (Nettention.Proud.RmiID)27008;
			public const Nettention.Proud.RmiID SkillUnEquipV2Req = (Nettention.Proud.RmiID)27009;
			public const Nettention.Proud.RmiID SkillUpgradeV2Req = (Nettention.Proud.RmiID)27010;
			public const Nettention.Proud.RmiID SkillUseV2Req = (Nettention.Proud.RmiID)27011;
			public const Nettention.Proud.RmiID RTTSkillUseV2Req = (Nettention.Proud.RmiID)27031;
			public const Nettention.Proud.RmiID RTTSkillHitV2Req = (Nettention.Proud.RmiID)27033;
			public const Nettention.Proud.RmiID PlayerTitleChangeV2Req = (Nettention.Proud.RmiID)28001;
			public const Nettention.Proud.RmiID TitleChangeV2Req = (Nettention.Proud.RmiID)28002;
			public const Nettention.Proud.RmiID TitleListV2Req = (Nettention.Proud.RmiID)28003;
			public const Nettention.Proud.RmiID TradeCronAverageBalanceReq = (Nettention.Proud.RmiID)29001;
			public const Nettention.Proud.RmiID TradeCronBalanceReq = (Nettention.Proud.RmiID)29002;
			public const Nettention.Proud.RmiID TradeCronBuyReq = (Nettention.Proud.RmiID)29003;
			public const Nettention.Proud.RmiID TradeCronInfoReq = (Nettention.Proud.RmiID)29004;
			public const Nettention.Proud.RmiID TradeCronListReq = (Nettention.Proud.RmiID)29005;
			public const Nettention.Proud.RmiID TradeCronPreviousDayBalanceReq = (Nettention.Proud.RmiID)29006;
			public const Nettention.Proud.RmiID TradeCronSellReq = (Nettention.Proud.RmiID)29007;
			public const Nettention.Proud.RmiID TradeCronWeeklyBalanceReq = (Nettention.Proud.RmiID)29008;
			public const Nettention.Proud.RmiID TradePersonalRequestReq = (Nettention.Proud.RmiID)29018;
			public const Nettention.Proud.RmiID TradePersonalAcceptReq = (Nettention.Proud.RmiID)29023;
			public const Nettention.Proud.RmiID TradePersonalRefuseReq = (Nettention.Proud.RmiID)29025;
			public const Nettention.Proud.RmiID TradePersonalCancelReq = (Nettention.Proud.RmiID)29027;
			public const Nettention.Proud.RmiID TradePersonalWithdrawReq = (Nettention.Proud.RmiID)29029;
			public const Nettention.Proud.RmiID TradePersonalFinishReq = (Nettention.Proud.RmiID)29031;
			public const Nettention.Proud.RmiID TradePersonalHistoryReq = (Nettention.Proud.RmiID)29033;
			public const Nettention.Proud.RmiID TradeCronMyListReq = (Nettention.Proud.RmiID)29035;
			public const Nettention.Proud.RmiID TradeCronSettleReq = (Nettention.Proud.RmiID)29037;
			public const Nettention.Proud.RmiID TradeCronTradesReq = (Nettention.Proud.RmiID)29039;
			public const Nettention.Proud.RmiID TradeCronTimeToNextChangeBalanceReq = (Nettention.Proud.RmiID)29041;
			public const Nettention.Proud.RmiID TradeCronCancelReq = (Nettention.Proud.RmiID)29043;
			public const Nettention.Proud.RmiID TradeCronReclaimExpiredReq = (Nettention.Proud.RmiID)29045;
			public const Nettention.Proud.RmiID TradeCronRemainingCanceledPenaltyTimeReq = (Nettention.Proud.RmiID)29047;
			public const Nettention.Proud.RmiID TradeItemRegistReq = (Nettention.Proud.RmiID)29052;
			public const Nettention.Proud.RmiID TradeItemCancelReq = (Nettention.Proud.RmiID)29054;
			public const Nettention.Proud.RmiID TradeItemBuyReq = (Nettention.Proud.RmiID)29056;
			public const Nettention.Proud.RmiID TradeItemWithdrawReq = (Nettention.Proud.RmiID)29058;
			public const Nettention.Proud.RmiID TradeItemFinishReq = (Nettention.Proud.RmiID)29060;
			public const Nettention.Proud.RmiID TradeItemHistoryReq = (Nettention.Proud.RmiID)29062;
			public const Nettention.Proud.RmiID TradeItemSearchCategoryReq = (Nettention.Proud.RmiID)29064;
			public const Nettention.Proud.RmiID TradeItemSearchItemIndexReq = (Nettention.Proud.RmiID)29066;
			public const Nettention.Proud.RmiID TradeItemBookmarkAddReq = (Nettention.Proud.RmiID)29069;
			public const Nettention.Proud.RmiID TradeItemBookmarkDeleteReq = (Nettention.Proud.RmiID)29071;
			public const Nettention.Proud.RmiID WeaponAppearanceCollectListV2Req = (Nettention.Proud.RmiID)30001;
			public const Nettention.Proud.RmiID WeaponAppearanceEquipV2Req = (Nettention.Proud.RmiID)30002;
			public const Nettention.Proud.RmiID WeaponAppearanceExtractFromItemV2Req = (Nettention.Proud.RmiID)30003;
			public const Nettention.Proud.RmiID WeaponAppearanceHiddenV2Req = (Nettention.Proud.RmiID)30004;
			public const Nettention.Proud.RmiID WeaponAppearanceListV2Req = (Nettention.Proud.RmiID)30005;
			public const Nettention.Proud.RmiID WeaponAppearanceUnequipV2Req = (Nettention.Proud.RmiID)30006;
			public const Nettention.Proud.RmiID AccountCreateNameReq = (Nettention.Proud.RmiID)40001;
			public const Nettention.Proud.RmiID ZoneStatusReq = (Nettention.Proud.RmiID)41001;
			public const Nettention.Proud.RmiID BloodFogEnterReq = (Nettention.Proud.RmiID)42001;
			public const Nettention.Proud.RmiID BloodFogLeaveReq = (Nettention.Proud.RmiID)42003;
			public const Nettention.Proud.RmiID BloodFogUseBuffReq = (Nettention.Proud.RmiID)42005;
			public const Nettention.Proud.RmiID C2SRttReq = (Nettention.Proud.RmiID)50001;
			public const Nettention.Proud.RmiID C2SRttRes = (Nettention.Proud.RmiID)50004;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			PlayerSelectReq,
			PlayerEnterStageFirstReq,
			PlayerEnterStageSecondReq,
			PlayerEnterStageThirdReq,
			PlayerEnterStageFourthReq,
			PlayerEnterStageFifthReq,
			PlayerGameEnterReq,
			AuthenticateBotCredentialReq,
			DesignateBindStoneReq,
			PortalByBindStoneReq,
			PlayerBlackRosterGetPreferenceReq,
			PlayerBlackRosterObservingReq,
			PlayerBlackRosterProvocationReq,
			PlayerBlackRosterRankReq,
			PlayerBlackRosterRevengeReq,
			PlayerBlackRosterSetPreferenceReq,
			PlayerBlackRostersReq,
			PlayerBlackRosterLastWeekRankReq,
			CheatMessageV2Req,
			AccountBlockPlayerAddReq,
			AccountBlockPlayerDeleteReq,
			AccountBlockPlayerReasonEditReq,
			AccountBlockPlayersReq,
			ChatMessageV2Req,
			PlayerSearchV2Req,
			LinkItemInfoReq,
			CostumeCardBuildReq,
			CostumeCardGachaReq,
			CostumeCardInfoReq,
			CostumeCardMixReq,
			CostumeCollectReq,
			CostumeEquipBodyReq,
			CostumeEquipBodyShowReq,
			CostumeEquipHeadReq,
			CostumeEquipHeadShowReq,
			CostumeInfoReq,
			CostumeConfirmAcceptReq,
			CostumeConfirmChangeReq,
			CostumeConfirmInfoReq,
			PortalEffectReq,
			AttainmentDailyRewardV2Req,
			AttainmentNormalRewardV2Req,
			AttendanceRewardV2Req,
			BossScheduleReq,
			EventExchangeRewardV2Req,
			GuildAdminBuffActiveReq,
			GuildAdminBuffBuyReq,
			GuildAdminInfoReq,
			GuildAdminLevelUpReq,
			GuildAdminMasterChangeReq,
			GuildAdminMemberBanishReq,
			GuildAdminMemberUpdateReq,
			GuildAdminUpdateBaseReq,
			GuildAdminUpdateIntroReq,
			GuildAdminUpdateNoticeReq,
			GuildAdminUpdateTendencyReq,
			GuildAdminUpdateTypeReq,
			GuildAttendReq,
			GuildBuffInfoReq,
			GuildCreateReq,
			GuildDeleteReq,
			GuildDonateReq,
			GuildDonationByCronV2Req,
			GuildFindReq,
			GuildHistroyReq,
			GuildInfoCallReq,
			GuildInfoReq,
			GuildJoinRequestConfirmReq,
			GuildJoinRequestListReq,
			GuildLeaveReq,
			GuildLiveInviteConfirmReq,
			GuildLiveInviteReq,
			GuildMemberInfoReq,
			GuildSignRequestCancelReq,
			GuildSignRequestListReq,
			GuildSignRequestReq,
			GuildVoteInfoReq,
			GuildVoteMasterImpeachReq,
			GuildVoteReq,
			GuildWaitingMemberListV2Req,
			GuildWarehouseChangeSizeV2Req,
			GuildWarehouseInfoV2Req,
			GuildWarehouseItemMoveV2Req,
			GuildWarehouseWalletMoveV2Req,
			GuildTerritoryInfoReq,
			GuildTerritorySetReq,
			WorldTerritoryOverviewReq,
			DungeonEnterV2Req,
			DungeonGiveUpV2Req,
			DungeonLeaveV2Req,
			DungeonLoadingCompleteV2Req,
			InteractStartReq,
			InteractEndReq,
			InteractCancelReq,
			EquipmentVisibleV2Req,
			InventoryChangeSizeV2Req,
			ItemAddOptionV2Req,
			ItemChangeOptionV2Req,
			ItemCollectionBookmarksRegisterV2Req,
			ItemCollectionBookmarksUnregisterV2Req,
			ItemCollectionRegisterV2Req,
			ItemCombineV2Req,
			ItemDeleteV2Req,
			ItemDisassembleV2Req,
			ItemEnchantV2Req,
			ItemEquipV2Req,
			ItemIntensionV2Req,
			ItemMixOptionV2Req,
			ItemPackageUseV2Req,
			ItemProductionV2Req,
			ItemSelectUseV2Req,
			ItemUpgradeV2Req,
			ItemUseV2Req,
			PkLootingItemV2Req,
			PkLootingListV2Req,
			WarehouseChangeSizeV2Req,
			WarehouseInfoV2Req,
			WarehouseItemMoveV2Req,
			ItemSetLockReq,
			ItemMarketPriceReq,
			ItemInheritReq,
			MailListV2Req,
			MailReadAllV2Req,
			MailReadV2Req,
			MatchingApplyReq,
			MatchingCancelReq,
			MatchingReplyReq,
			AuthenticatePlayerCredentialReq,
			BroadCastContextReq,
			CutSceneEndV2Req,
			CutSceneStartV2Req,
			LogOutReq,
			PortalV2Req,
			ReturnToLobbyReq,
			ServerTimeV2Req,
			TestPacketV2Req,
			TriggerActivateV2Req,
			UnionV2Req,
			ZoneLoadingCompletedReq,
			BossDamagedInfoReq,
			PartyChangeLootingReq,
			PartyCreateReq,
			PartyDisbandReq,
			PartyDungeonEntranceInquiryReq,
			PartyEnterDungeonReplyReq,
			PartyEnterDungeonReq,
			PartyInfoReq,
			PartyInviteReplyReq,
			PartyInviteReq,
			PartyLeaderChangeReq,
			PartyLeaveReq,
			PartyMemberKickReq,
			PartySuggestionPlayersReq,
			PartyEnterDungeonCanceledReq,
			PetCollectInfoV2Req,
			PetEquipOffV2Req,
			PetEquipV2Req,
			PetFeedUseV2Req,
			PetGachaV2Req,
			PetInfoV2Req,
			PetMixV2Req,
			PetUpgradeV2Req,
			PetInActiveBuffReq,
			PhaseFieldEndV2Req,
			PhaseFieldStartV2Req,
			PlayerDeleteReq,
			PlayerGetMacroReq,
			PlayerMapMoveV2Req,
			PlayerMoveV2Req,
			PlayerMoveZoneV2Req,
			PlayerResurrectionV2Req,
			PlayerSetMacroReq,
			PlayerSlotChangeV2Req,
			PlayerStatPointChangeV2Req,
			PlayerStatPointInitV2Req,
			PlayerStatV2Req,
			PlayerDeathInfoReq,
			RecoverPlayerExpReq,
			PlayerClassUpV2Req,
			QuickslotSetReq,
			PlayerExpRecoveryPopupReq,
			RTTPlayerMoveV2Req,
			QuestAbandonV2Req,
			QuestAcceptV2Req,
			QuestCompleteV2Req,
			QuestConditionCompleteV2Req,
			QuestListV2Req,
			QuestPortalV2Req,
			QuestRegisterV2Req,
			QuestRerollV2Req,
			QuestRewardV2Req,
			QuestTalkCompleteV2Req,
			TutorialSkipV2Req,
			GuildRelationReq,
			PlayerRelationReq,
			RideAttachDeleteV2Req,
			RideAttachDisassembleV2Req,
			RideAttachEquipOffV2Req,
			RideAttachEquipV2Req,
			RideAttachGachaV2Req,
			RideAttachInvenExtendV2Req,
			RideEquipOffV2Req,
			RideEquipV2Req,
			RideGachaV2Req,
			RideMixV2Req,
			RideSitOffV2Req,
			RideSitV2Req,
			BuyCashShopItemV2Req,
			BuyGameShopItemV2Req,
			GameShopSellItemV2Req,
			ChangeSiegeModeV2Req,
			ChoiceSiegeWarFactionV2Req,
			GetSiegeWarInfoV2Req,
			GetSiegeWarMatchInfoV2Req,
			BuffListInfoV2Req,
			SkillChangeAutoUseV2Req,
			SkillChangePresetV2Req,
			SkillEquipV2Req,
			SkillHitV2Req,
			SkillLearnV2Req,
			SkillLevelUpV2Req,
			SkillListInfoV2Req,
			SkillUnEquipV2Req,
			SkillUpgradeV2Req,
			SkillUseV2Req,
			RTTSkillUseV2Req,
			RTTSkillHitV2Req,
			PlayerTitleChangeV2Req,
			TitleChangeV2Req,
			TitleListV2Req,
			TradeCronAverageBalanceReq,
			TradeCronBalanceReq,
			TradeCronBuyReq,
			TradeCronInfoReq,
			TradeCronListReq,
			TradeCronPreviousDayBalanceReq,
			TradeCronSellReq,
			TradeCronWeeklyBalanceReq,
			TradePersonalRequestReq,
			TradePersonalAcceptReq,
			TradePersonalRefuseReq,
			TradePersonalCancelReq,
			TradePersonalWithdrawReq,
			TradePersonalFinishReq,
			TradePersonalHistoryReq,
			TradeCronMyListReq,
			TradeCronSettleReq,
			TradeCronTradesReq,
			TradeCronTimeToNextChangeBalanceReq,
			TradeCronCancelReq,
			TradeCronReclaimExpiredReq,
			TradeCronRemainingCanceledPenaltyTimeReq,
			TradeItemRegistReq,
			TradeItemCancelReq,
			TradeItemBuyReq,
			TradeItemWithdrawReq,
			TradeItemFinishReq,
			TradeItemHistoryReq,
			TradeItemSearchCategoryReq,
			TradeItemSearchItemIndexReq,
			TradeItemBookmarkAddReq,
			TradeItemBookmarkDeleteReq,
			WeaponAppearanceCollectListV2Req,
			WeaponAppearanceEquipV2Req,
			WeaponAppearanceExtractFromItemV2Req,
			WeaponAppearanceHiddenV2Req,
			WeaponAppearanceListV2Req,
			WeaponAppearanceUnequipV2Req,
			AccountCreateNameReq,
			ZoneStatusReq,
			BloodFogEnterReq,
			BloodFogLeaveReq,
			BloodFogUseBuffReq,
			C2SRttReq,
			C2SRttRes,
		};
	}
}






				 
