 





// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
            
using System.Collections.Generic; 
namespace NetProtocol.Packet.G2C
{
	public class Common
	{
		// Message ID that replies to each RMI method. 
			public const Nettention.Proud.RmiID PlayerSelectRes = (Nettention.Proud.RmiID)1008;
			public const Nettention.Proud.RmiID PlayerEnterStageFirstRes = (Nettention.Proud.RmiID)1009;
			public const Nettention.Proud.RmiID PlayerEnterStageSecondRes = (Nettention.Proud.RmiID)1010;
			public const Nettention.Proud.RmiID PlayerEnterStageThirdRes = (Nettention.Proud.RmiID)1011;
			public const Nettention.Proud.RmiID PlayerEnterStageFourthRes = (Nettention.Proud.RmiID)1012;
			public const Nettention.Proud.RmiID PlayerEnterStageFifthRes = (Nettention.Proud.RmiID)1013;
			public const Nettention.Proud.RmiID PlayerGameEnterRes = (Nettention.Proud.RmiID)1014;
			public const Nettention.Proud.RmiID AuthenticateBotCredentialRes = (Nettention.Proud.RmiID)1016;
			public const Nettention.Proud.RmiID ActorAddBuffV2Noti = (Nettention.Proud.RmiID)2001;
			public const Nettention.Proud.RmiID ActorChangedLevelToMeV2Noti = (Nettention.Proud.RmiID)2002;
			public const Nettention.Proud.RmiID ActorChangedLevelV2Noti = (Nettention.Proud.RmiID)2003;
			public const Nettention.Proud.RmiID ActorChangeStateV2Noti = (Nettention.Proud.RmiID)2004;
			public const Nettention.Proud.RmiID ActorCostumeNoti = (Nettention.Proud.RmiID)2005;
			public const Nettention.Proud.RmiID ActorDeathV2Noti = (Nettention.Proud.RmiID)2006;
			public const Nettention.Proud.RmiID ActorDisAppearV2Noti = (Nettention.Proud.RmiID)2007;
			public const Nettention.Proud.RmiID ActorGuildV2Noti = (Nettention.Proud.RmiID)2008;
			public const Nettention.Proud.RmiID ActorHpMpUpdateV2Noti = (Nettention.Proud.RmiID)2009;
			public const Nettention.Proud.RmiID ActorHpUpdateV2Noti = (Nettention.Proud.RmiID)2010;
			public const Nettention.Proud.RmiID ActorMoveV2Noti = (Nettention.Proud.RmiID)2011;
			public const Nettention.Proud.RmiID ActorMpUpdateV2Noti = (Nettention.Proud.RmiID)2012;
			public const Nettention.Proud.RmiID ActorPetV2Noti = (Nettention.Proud.RmiID)2013;
			public const Nettention.Proud.RmiID ActorRemoveBuffV2Noti = (Nettention.Proud.RmiID)2014;
			public const Nettention.Proud.RmiID ActorRideV2Noti = (Nettention.Proud.RmiID)2015;
			public const Nettention.Proud.RmiID ActorsDisAppearV2Noti = (Nettention.Proud.RmiID)2016;
			public const Nettention.Proud.RmiID MonsterActorAppearV2Noti = (Nettention.Proud.RmiID)2017;
			public const Nettention.Proud.RmiID MonsterActorsAppearV2Noti = (Nettention.Proud.RmiID)2018;
			public const Nettention.Proud.RmiID MonsterActorTargetNoti = (Nettention.Proud.RmiID)2019;
			public const Nettention.Proud.RmiID PlayerActorAppearV2Noti = (Nettention.Proud.RmiID)2020;
			public const Nettention.Proud.RmiID PlayerActorsAppearV2Noti = (Nettention.Proud.RmiID)2021;
			public const Nettention.Proud.RmiID PlayerActorZoneStateNoti = (Nettention.Proud.RmiID)2022;
			public const Nettention.Proud.RmiID ActorStatSyncNoti = (Nettention.Proud.RmiID)2023;
			public const Nettention.Proud.RmiID PropActorAppearNoti = (Nettention.Proud.RmiID)2024;
			public const Nettention.Proud.RmiID ActorPendingDisAppearNoti = (Nettention.Proud.RmiID)2025;
			public const Nettention.Proud.RmiID PropActorsAppearNoti = (Nettention.Proud.RmiID)2026;
			public const Nettention.Proud.RmiID DesignateBindStoneRes = (Nettention.Proud.RmiID)3003;
			public const Nettention.Proud.RmiID PortalByBindStoneRes = (Nettention.Proud.RmiID)3004;
			public const Nettention.Proud.RmiID PlayerBlackRosterGetPreferenceRes = (Nettention.Proud.RmiID)4008;
			public const Nettention.Proud.RmiID PlayerBlackRosterObservingNoti = (Nettention.Proud.RmiID)4009;
			public const Nettention.Proud.RmiID PlayerBlackRosterObservingRes = (Nettention.Proud.RmiID)4010;
			public const Nettention.Proud.RmiID PlayerBlackRosterProvocationNoti = (Nettention.Proud.RmiID)4011;
			public const Nettention.Proud.RmiID PlayerBlackRosterProvocationRes = (Nettention.Proud.RmiID)4012;
			public const Nettention.Proud.RmiID PlayerBlackRosterRankRes = (Nettention.Proud.RmiID)4013;
			public const Nettention.Proud.RmiID PlayerBlackRosterRevengeRes = (Nettention.Proud.RmiID)4014;
			public const Nettention.Proud.RmiID PlayerBlackRosterSetPreferenceRes = (Nettention.Proud.RmiID)4015;
			public const Nettention.Proud.RmiID PlayerBlackRostersRes = (Nettention.Proud.RmiID)4016;
			public const Nettention.Proud.RmiID PlayerBlackRosterLastWeekRankRes = (Nettention.Proud.RmiID)4018;
			public const Nettention.Proud.RmiID PlayerBlackRosterMessageNoti = (Nettention.Proud.RmiID)4019;
			public const Nettention.Proud.RmiID CheatGetMainQuestV2Noti = (Nettention.Proud.RmiID)6002;
			public const Nettention.Proud.RmiID CheatMessageV2Res = (Nettention.Proud.RmiID)6003;
			public const Nettention.Proud.RmiID CheatQuestResetV2Noti = (Nettention.Proud.RmiID)6004;
			public const Nettention.Proud.RmiID AccountBlockPlayerAddRes = (Nettention.Proud.RmiID)7007;
			public const Nettention.Proud.RmiID AccountBlockPlayerDeleteRes = (Nettention.Proud.RmiID)7008;
			public const Nettention.Proud.RmiID AccountBlockPlayerReasonEditRes = (Nettention.Proud.RmiID)7009;
			public const Nettention.Proud.RmiID AccountBlockPlayersRes = (Nettention.Proud.RmiID)7010;
			public const Nettention.Proud.RmiID ChatMessageV2Noti = (Nettention.Proud.RmiID)7011;
			public const Nettention.Proud.RmiID ChatMessageV2Res = (Nettention.Proud.RmiID)7012;
			public const Nettention.Proud.RmiID PlayerSearchV2Res = (Nettention.Proud.RmiID)7013;
			public const Nettention.Proud.RmiID LinkItemInfoRes = (Nettention.Proud.RmiID)7015;
			public const Nettention.Proud.RmiID CostumeCardBuildRes = (Nettention.Proud.RmiID)8002;
			public const Nettention.Proud.RmiID CostumeCardGachaRes = (Nettention.Proud.RmiID)8004;
			public const Nettention.Proud.RmiID CostumeCardInfoRes = (Nettention.Proud.RmiID)8006;
			public const Nettention.Proud.RmiID CostumeCardMixRes = (Nettention.Proud.RmiID)8008;
			public const Nettention.Proud.RmiID CostumeCollectNoti = (Nettention.Proud.RmiID)8010;
			public const Nettention.Proud.RmiID CostumeCollectRes = (Nettention.Proud.RmiID)8011;
			public const Nettention.Proud.RmiID CostumeEquipBodyRes = (Nettention.Proud.RmiID)8013;
			public const Nettention.Proud.RmiID CostumeEquipBodyShowRes = (Nettention.Proud.RmiID)8015;
			public const Nettention.Proud.RmiID CostumeEquipHeadRes = (Nettention.Proud.RmiID)8017;
			public const Nettention.Proud.RmiID CostumeEquipHeadShowRes = (Nettention.Proud.RmiID)8019;
			public const Nettention.Proud.RmiID CostumeInfoRes = (Nettention.Proud.RmiID)8021;
			public const Nettention.Proud.RmiID CostumeConfirmAcceptRes = (Nettention.Proud.RmiID)8025;
			public const Nettention.Proud.RmiID CostumeConfirmChangeRes = (Nettention.Proud.RmiID)8026;
			public const Nettention.Proud.RmiID CostumeConfirmInfoRes = (Nettention.Proud.RmiID)8027;
			public const Nettention.Proud.RmiID PortalEffectNoti = (Nettention.Proud.RmiID)9002;
			public const Nettention.Proud.RmiID PortalEffectRes = (Nettention.Proud.RmiID)9003;
			public const Nettention.Proud.RmiID AttainmentDailyRewardV2Res = (Nettention.Proud.RmiID)10006;
			public const Nettention.Proud.RmiID AttainmentNormalRewardV2Res = (Nettention.Proud.RmiID)10007;
			public const Nettention.Proud.RmiID AttainmentProgressV2Noti = (Nettention.Proud.RmiID)10008;
			public const Nettention.Proud.RmiID AttainmentsNoti = (Nettention.Proud.RmiID)10009;
			public const Nettention.Proud.RmiID AttendanceRewardV2Res = (Nettention.Proud.RmiID)10010;
			public const Nettention.Proud.RmiID BossScheduleNoti = (Nettention.Proud.RmiID)10011;
			public const Nettention.Proud.RmiID BossScheduleRes = (Nettention.Proud.RmiID)10012;
			public const Nettention.Proud.RmiID EventAttendanceListV2Noti = (Nettention.Proud.RmiID)10013;
			public const Nettention.Proud.RmiID EventExchangeRewardV2Res = (Nettention.Proud.RmiID)10014;
			public const Nettention.Proud.RmiID GuildAdminBuffActiveRes = (Nettention.Proud.RmiID)11040;
			public const Nettention.Proud.RmiID GuildAdminBuffBuyRes = (Nettention.Proud.RmiID)11041;
			public const Nettention.Proud.RmiID GuildAdminInfoRes = (Nettention.Proud.RmiID)11042;
			public const Nettention.Proud.RmiID GuildAdminMasterChangeNoti = (Nettention.Proud.RmiID)11043;
			public const Nettention.Proud.RmiID GuildAdminMasterChangeRes = (Nettention.Proud.RmiID)11044;
			public const Nettention.Proud.RmiID GuildAdminMemberBanishNoti = (Nettention.Proud.RmiID)11045;
			public const Nettention.Proud.RmiID GuildAdminMemberBanishRes = (Nettention.Proud.RmiID)11046;
			public const Nettention.Proud.RmiID GuildAdminMemberUpdateNoti = (Nettention.Proud.RmiID)11047;
			public const Nettention.Proud.RmiID GuildAdminMemberUpdateRes = (Nettention.Proud.RmiID)11048;
			public const Nettention.Proud.RmiID GuildAdminUpdateBaseNoti = (Nettention.Proud.RmiID)11049;
			public const Nettention.Proud.RmiID GuildAdminUpdateBaseRes = (Nettention.Proud.RmiID)11050;
			public const Nettention.Proud.RmiID GuildAdminUpdateIntroNoti = (Nettention.Proud.RmiID)11051;
			public const Nettention.Proud.RmiID GuildAdminUpdateIntroRes = (Nettention.Proud.RmiID)11052;
			public const Nettention.Proud.RmiID GuildAdminUpdateNoticeNoti = (Nettention.Proud.RmiID)11053;
			public const Nettention.Proud.RmiID GuildAdminUpdateNoticeRes = (Nettention.Proud.RmiID)11054;
			public const Nettention.Proud.RmiID GuildAdminUpdateTendencyNoti = (Nettention.Proud.RmiID)11055;
			public const Nettention.Proud.RmiID GuildAdminUpdateTendencyRes = (Nettention.Proud.RmiID)11056;
			public const Nettention.Proud.RmiID GuildAdminUpdateTypeNoti = (Nettention.Proud.RmiID)11057;
			public const Nettention.Proud.RmiID GuildAdminUpdateTypeRes = (Nettention.Proud.RmiID)11058;
			public const Nettention.Proud.RmiID GuildAttendRes = (Nettention.Proud.RmiID)11059;
			public const Nettention.Proud.RmiID GuildBaseNoti = (Nettention.Proud.RmiID)11060;
			public const Nettention.Proud.RmiID GuildBuffInfoRes = (Nettention.Proud.RmiID)11061;
			public const Nettention.Proud.RmiID GuildBuffNoti = (Nettention.Proud.RmiID)11062;
			public const Nettention.Proud.RmiID GuildCreateRes = (Nettention.Proud.RmiID)11063;
			public const Nettention.Proud.RmiID GuildDeleteRes = (Nettention.Proud.RmiID)11064;
			public const Nettention.Proud.RmiID GuildDonateRes = (Nettention.Proud.RmiID)11065;
			public const Nettention.Proud.RmiID GuildDonationByCronV2Res = (Nettention.Proud.RmiID)11066;
			public const Nettention.Proud.RmiID GuildFindRes = (Nettention.Proud.RmiID)11067;
			public const Nettention.Proud.RmiID GuildHistoryNoti = (Nettention.Proud.RmiID)11068;
			public const Nettention.Proud.RmiID GuildHistoryRes = (Nettention.Proud.RmiID)11069;
			public const Nettention.Proud.RmiID GuildInfoCallRes = (Nettention.Proud.RmiID)11070;
			public const Nettention.Proud.RmiID GuildInfoRes = (Nettention.Proud.RmiID)11071;
			public const Nettention.Proud.RmiID GuildJoinRequestConfirmNoti = (Nettention.Proud.RmiID)11072;
			public const Nettention.Proud.RmiID GuildJoinRequestConfirmRes = (Nettention.Proud.RmiID)11073;
			public const Nettention.Proud.RmiID GuildJoinRequestListRes = (Nettention.Proud.RmiID)11074;
			public const Nettention.Proud.RmiID GuildLeaveNoti = (Nettention.Proud.RmiID)11075;
			public const Nettention.Proud.RmiID GuildLeaveRes = (Nettention.Proud.RmiID)11076;
			public const Nettention.Proud.RmiID GuildLiveInviteConfirmNoti = (Nettention.Proud.RmiID)11077;
			public const Nettention.Proud.RmiID GuildLiveInviteConfirmRes = (Nettention.Proud.RmiID)11078;
			public const Nettention.Proud.RmiID GuildLiveInviteNoti = (Nettention.Proud.RmiID)11079;
			public const Nettention.Proud.RmiID GuildLiveInviteRes = (Nettention.Proud.RmiID)11080;
			public const Nettention.Proud.RmiID GuildMemberInfoRes = (Nettention.Proud.RmiID)11081;
			public const Nettention.Proud.RmiID GuildMemberNoti = (Nettention.Proud.RmiID)11082;
			public const Nettention.Proud.RmiID GuildMemberStateV2Noti = (Nettention.Proud.RmiID)11083;
			public const Nettention.Proud.RmiID GuildMemberUpdateNoti = (Nettention.Proud.RmiID)11084;
			public const Nettention.Proud.RmiID GuildPointNoti = (Nettention.Proud.RmiID)11085;
			public const Nettention.Proud.RmiID GuildSignRequestCancelRes = (Nettention.Proud.RmiID)11086;
			public const Nettention.Proud.RmiID GuildSignRequestListRes = (Nettention.Proud.RmiID)11087;
			public const Nettention.Proud.RmiID GuildSignRequestRes = (Nettention.Proud.RmiID)11088;
			public const Nettention.Proud.RmiID GuildUpdateCrestNoti = (Nettention.Proud.RmiID)11089;
			public const Nettention.Proud.RmiID GuildUpdateCurrencyV2Noti = (Nettention.Proud.RmiID)11090;
			public const Nettention.Proud.RmiID GuildVoteInfoRes = (Nettention.Proud.RmiID)11091;
			public const Nettention.Proud.RmiID GuildVoteMasterImpeachRes = (Nettention.Proud.RmiID)11092;
			public const Nettention.Proud.RmiID GuildVoteNoti = (Nettention.Proud.RmiID)11093;
			public const Nettention.Proud.RmiID GuildVoteRes = (Nettention.Proud.RmiID)11094;
			public const Nettention.Proud.RmiID GuildWarehouseChangeSizeV2Res = (Nettention.Proud.RmiID)11095;
			public const Nettention.Proud.RmiID GuildWarehouseInfoV2Res = (Nettention.Proud.RmiID)11096;
			public const Nettention.Proud.RmiID GuildWarehouseItemMoveV2Res = (Nettention.Proud.RmiID)11097;
			public const Nettention.Proud.RmiID GuildWarehouseWalletMoveV2Res = (Nettention.Proud.RmiID)11098;
			public const Nettention.Proud.RmiID GuildRubyNoti = (Nettention.Proud.RmiID)11099;
			public const Nettention.Proud.RmiID GuildCronNoti = (Nettention.Proud.RmiID)11100;
			public const Nettention.Proud.RmiID GuildTerritoryInfoRes = (Nettention.Proud.RmiID)11102;
			public const Nettention.Proud.RmiID GuildTerritorySetRes = (Nettention.Proud.RmiID)11104;
			public const Nettention.Proud.RmiID WorldTerritoryOverviewRes = (Nettention.Proud.RmiID)11106;
			public const Nettention.Proud.RmiID WorldBossLastAttackNoti = (Nettention.Proud.RmiID)11107;
			public const Nettention.Proud.RmiID DungeonClearHistoryV2Noti = (Nettention.Proud.RmiID)12005;
			public const Nettention.Proud.RmiID DungeonClearV2Noti = (Nettention.Proud.RmiID)12006;
			public const Nettention.Proud.RmiID DungeonCronUpdateV2Noti = (Nettention.Proud.RmiID)12007;
			public const Nettention.Proud.RmiID DungeonEnterV2Res = (Nettention.Proud.RmiID)12008;
			public const Nettention.Proud.RmiID DungeonExpUpdateV2Noti = (Nettention.Proud.RmiID)12009;
			public const Nettention.Proud.RmiID DungeonGiveUpV2Res = (Nettention.Proud.RmiID)12010;
			public const Nettention.Proud.RmiID DungeonLeaveV2Res = (Nettention.Proud.RmiID)12011;
			public const Nettention.Proud.RmiID DungeonLoadingCompleteAllV2Noti = (Nettention.Proud.RmiID)12012;
			public const Nettention.Proud.RmiID DungeonLoadingCompleteV2Res = (Nettention.Proud.RmiID)12013;
			public const Nettention.Proud.RmiID ExpDungeonClearNoti = (Nettention.Proud.RmiID)12014;
			public const Nettention.Proud.RmiID EquipDungeonClearNoti = (Nettention.Proud.RmiID)12015;
			public const Nettention.Proud.RmiID MineralDungeonClearNoti = (Nettention.Proud.RmiID)12016;
			public const Nettention.Proud.RmiID PartyDungeonClearNoti = (Nettention.Proud.RmiID)12017;
			public const Nettention.Proud.RmiID InteractStartRes = (Nettention.Proud.RmiID)13002;
			public const Nettention.Proud.RmiID InteractEndRes = (Nettention.Proud.RmiID)13004;
			public const Nettention.Proud.RmiID InteractCancelRes = (Nettention.Proud.RmiID)13006;
			public const Nettention.Proud.RmiID InteractNoti = (Nettention.Proud.RmiID)13007;
			public const Nettention.Proud.RmiID EquipmentVisibleV2Res = (Nettention.Proud.RmiID)14025;
			public const Nettention.Proud.RmiID InventoryChangeSizeV2Res = (Nettention.Proud.RmiID)14026;
			public const Nettention.Proud.RmiID ItemAddOptionV2Res = (Nettention.Proud.RmiID)14027;
			public const Nettention.Proud.RmiID ItemAddV2Noti = (Nettention.Proud.RmiID)14028;
			public const Nettention.Proud.RmiID ItemChangeOptionV2Res = (Nettention.Proud.RmiID)14029;
			public const Nettention.Proud.RmiID ItemCollectionBookmarksRegisterV2Res = (Nettention.Proud.RmiID)14030;
			public const Nettention.Proud.RmiID ItemCollectionBookmarksUnregisterV2Res = (Nettention.Proud.RmiID)14031;
			public const Nettention.Proud.RmiID ItemCollectionListV2Noti = (Nettention.Proud.RmiID)14032;
			public const Nettention.Proud.RmiID ItemCollectionRegisterV2Res = (Nettention.Proud.RmiID)14033;
			public const Nettention.Proud.RmiID ItemCombineV2Res = (Nettention.Proud.RmiID)14034;
			public const Nettention.Proud.RmiID ItemDeleteV2Noti = (Nettention.Proud.RmiID)14035;
			public const Nettention.Proud.RmiID ItemDeleteV2Res = (Nettention.Proud.RmiID)14036;
			public const Nettention.Proud.RmiID ItemDisassembleV2Res = (Nettention.Proud.RmiID)14037;
			public const Nettention.Proud.RmiID ItemEnchantV2Res = (Nettention.Proud.RmiID)14038;
			public const Nettention.Proud.RmiID ItemEquipV2Noti = (Nettention.Proud.RmiID)14039;
			public const Nettention.Proud.RmiID ItemEquipV2Res = (Nettention.Proud.RmiID)14040;
			public const Nettention.Proud.RmiID ItemIntensionV2Res = (Nettention.Proud.RmiID)14041;
			public const Nettention.Proud.RmiID ItemMixOptionV2Res = (Nettention.Proud.RmiID)14042;
			public const Nettention.Proud.RmiID ItemPackageUseV2Res = (Nettention.Proud.RmiID)14043;
			public const Nettention.Proud.RmiID ItemProductionV2Res = (Nettention.Proud.RmiID)14044;
			public const Nettention.Proud.RmiID ItemSelectUseV2Res = (Nettention.Proud.RmiID)14045;
			public const Nettention.Proud.RmiID ItemUpdateV2Noti = (Nettention.Proud.RmiID)14046;
			public const Nettention.Proud.RmiID ItemUpgradeV2Res = (Nettention.Proud.RmiID)14047;
			public const Nettention.Proud.RmiID ItemUseV2Res = (Nettention.Proud.RmiID)14048;
			public const Nettention.Proud.RmiID PkLootingAddV2Noti = (Nettention.Proud.RmiID)14049;
			public const Nettention.Proud.RmiID PkLootingItemV2Res = (Nettention.Proud.RmiID)14050;
			public const Nettention.Proud.RmiID PkLootingListV2Res = (Nettention.Proud.RmiID)14051;
			public const Nettention.Proud.RmiID PkLootingV2Noti = (Nettention.Proud.RmiID)14052;
			public const Nettention.Proud.RmiID PlayerInventoryExtendInfoNoti = (Nettention.Proud.RmiID)14053;
			public const Nettention.Proud.RmiID PlayerInventoryInfoV2Noti = (Nettention.Proud.RmiID)14054;
			public const Nettention.Proud.RmiID WarehouseChangeSizeV2Res = (Nettention.Proud.RmiID)14055;
			public const Nettention.Proud.RmiID WarehouseInfoV2Res = (Nettention.Proud.RmiID)14056;
			public const Nettention.Proud.RmiID WarehouseItemMoveV2Res = (Nettention.Proud.RmiID)14057;
			public const Nettention.Proud.RmiID ItemIntentionSucceedNoti = (Nettention.Proud.RmiID)14058;
			public const Nettention.Proud.RmiID ItemSetLockRes = (Nettention.Proud.RmiID)14060;
			public const Nettention.Proud.RmiID ItemMarketPriceRes = (Nettention.Proud.RmiID)14062;
			public const Nettention.Proud.RmiID ItemInheritRes = (Nettention.Proud.RmiID)14064;
			public const Nettention.Proud.RmiID MailListV2Res = (Nettention.Proud.RmiID)15004;
			public const Nettention.Proud.RmiID MailReadAllV2Res = (Nettention.Proud.RmiID)15005;
			public const Nettention.Proud.RmiID MailReadV2Res = (Nettention.Proud.RmiID)15006;
			public const Nettention.Proud.RmiID MatchingApplyRes = (Nettention.Proud.RmiID)16004;
			public const Nettention.Proud.RmiID MatchingCancelRes = (Nettention.Proud.RmiID)16005;
			public const Nettention.Proud.RmiID MatchingCompleteNoti = (Nettention.Proud.RmiID)16006;
			public const Nettention.Proud.RmiID MatchingIncompleteNoti = (Nettention.Proud.RmiID)16007;
			public const Nettention.Proud.RmiID MatchingMatchedNoti = (Nettention.Proud.RmiID)16008;
			public const Nettention.Proud.RmiID MatchingRejectReplyNoti = (Nettention.Proud.RmiID)16009;
			public const Nettention.Proud.RmiID MatchingReplyNoti = (Nettention.Proud.RmiID)16010;
			public const Nettention.Proud.RmiID MatchingReplyRes = (Nettention.Proud.RmiID)16011;
			public const Nettention.Proud.RmiID AuthenticatePlayerCredentialRes = (Nettention.Proud.RmiID)17013;
			public const Nettention.Proud.RmiID BindStonesNoti = (Nettention.Proud.RmiID)17014;
			public const Nettention.Proud.RmiID BroadCastContextNoti = (Nettention.Proud.RmiID)17015;
			public const Nettention.Proud.RmiID BroadCastContextRes = (Nettention.Proud.RmiID)17016;
			public const Nettention.Proud.RmiID CutSceneEndV2Res = (Nettention.Proud.RmiID)17017;
			public const Nettention.Proud.RmiID CutSceneStartV2Res = (Nettention.Proud.RmiID)17018;
			public const Nettention.Proud.RmiID CutSceneStateV2Noti = (Nettention.Proud.RmiID)17019;
			public const Nettention.Proud.RmiID DebugPlayerStateV2Noti = (Nettention.Proud.RmiID)17020;
			public const Nettention.Proud.RmiID LogOutRes = (Nettention.Proud.RmiID)17021;
			public const Nettention.Proud.RmiID PortalV2Res = (Nettention.Proud.RmiID)17023;
			public const Nettention.Proud.RmiID ReturnToLobbyRes = (Nettention.Proud.RmiID)17024;
			public const Nettention.Proud.RmiID ServerTimeV2Res = (Nettention.Proud.RmiID)17025;
			public const Nettention.Proud.RmiID SystemMessageV2Noti = (Nettention.Proud.RmiID)17026;
			public const Nettention.Proud.RmiID TemporalFluxZoneEnterNoti = (Nettention.Proud.RmiID)17027;
			public const Nettention.Proud.RmiID TemporalFluxZoneExitNoti = (Nettention.Proud.RmiID)17028;
			public const Nettention.Proud.RmiID TestPacketV2Noti = (Nettention.Proud.RmiID)17029;
			public const Nettention.Proud.RmiID TestPacketV2Res = (Nettention.Proud.RmiID)17030;
			public const Nettention.Proud.RmiID TicketInfoV2Noti = (Nettention.Proud.RmiID)17031;
			public const Nettention.Proud.RmiID TriggerActivateMapMoveV2Noti = (Nettention.Proud.RmiID)17032;
			public const Nettention.Proud.RmiID TriggerActivateV2Res = (Nettention.Proud.RmiID)17033;
			public const Nettention.Proud.RmiID UnionV2Res = (Nettention.Proud.RmiID)17034;
			public const Nettention.Proud.RmiID ZoneLoadingCompletedRes = (Nettention.Proud.RmiID)17035;
			public const Nettention.Proud.RmiID BossDamagedInfoNoti = (Nettention.Proud.RmiID)17036;
			public const Nettention.Proud.RmiID BossFirstDamagedNoti = (Nettention.Proud.RmiID)17037;
			public const Nettention.Proud.RmiID BossKilledNoti = (Nettention.Proud.RmiID)17038;
			public const Nettention.Proud.RmiID BossKilledRewardNoti = (Nettention.Proud.RmiID)17039;
			public const Nettention.Proud.RmiID GainMessageNoti = (Nettention.Proud.RmiID)17040;
			public const Nettention.Proud.RmiID TicketUpdateNoti = (Nettention.Proud.RmiID)17041;
			public const Nettention.Proud.RmiID BossDamagedInfoRes = (Nettention.Proud.RmiID)17043;
			public const Nettention.Proud.RmiID WorldBossDamagedInfoNoti = (Nettention.Proud.RmiID)17044;
			public const Nettention.Proud.RmiID BossTakenDamageOnPlayerKillNoti = (Nettention.Proud.RmiID)17045;
			public const Nettention.Proud.RmiID PartyChangeLootingNoti = (Nettention.Proud.RmiID)18014;
			public const Nettention.Proud.RmiID PartyChangeLootingRes = (Nettention.Proud.RmiID)18015;
			public const Nettention.Proud.RmiID PartyCreateRes = (Nettention.Proud.RmiID)18016;
			public const Nettention.Proud.RmiID PartyDisbandNoti = (Nettention.Proud.RmiID)18017;
			public const Nettention.Proud.RmiID PartyDisbandRes = (Nettention.Proud.RmiID)18018;
			public const Nettention.Proud.RmiID PartyDungeonEntranceInquiryRes = (Nettention.Proud.RmiID)18019;
			public const Nettention.Proud.RmiID PartyEnterDungeonCanceledNoti = (Nettention.Proud.RmiID)18020;
			public const Nettention.Proud.RmiID PartyEnterDungeonNoti = (Nettention.Proud.RmiID)18021;
			public const Nettention.Proud.RmiID PartyEnterDungeonReplyNoti = (Nettention.Proud.RmiID)18022;
			public const Nettention.Proud.RmiID PartyEnterDungeonReplyRes = (Nettention.Proud.RmiID)18023;
			public const Nettention.Proud.RmiID PartyEnterDungeonRes = (Nettention.Proud.RmiID)18024;
			public const Nettention.Proud.RmiID PartyEnterNoti = (Nettention.Proud.RmiID)18025;
			public const Nettention.Proud.RmiID PartyInfoNoti = (Nettention.Proud.RmiID)18026;
			public const Nettention.Proud.RmiID PartyInfoRes = (Nettention.Proud.RmiID)18027;
			public const Nettention.Proud.RmiID PartyInviteNoti = (Nettention.Proud.RmiID)18028;
			public const Nettention.Proud.RmiID PartyInviteReplyNoti = (Nettention.Proud.RmiID)18029;
			public const Nettention.Proud.RmiID PartyInviteReplyRes = (Nettention.Proud.RmiID)18030;
			public const Nettention.Proud.RmiID PartyInviteRes = (Nettention.Proud.RmiID)18031;
			public const Nettention.Proud.RmiID PartyKickedNoti = (Nettention.Proud.RmiID)18032;
			public const Nettention.Proud.RmiID PartyLeaderChangeNoti = (Nettention.Proud.RmiID)18033;
			public const Nettention.Proud.RmiID PartyLeaderChangeRes = (Nettention.Proud.RmiID)18034;
			public const Nettention.Proud.RmiID PartyLeaveNoti = (Nettention.Proud.RmiID)18035;
			public const Nettention.Proud.RmiID PartyLeaveRes = (Nettention.Proud.RmiID)18036;
			public const Nettention.Proud.RmiID PartyMemberKickNoti = (Nettention.Proud.RmiID)18037;
			public const Nettention.Proud.RmiID PartyMemberKickRes = (Nettention.Proud.RmiID)18038;
			public const Nettention.Proud.RmiID PartyMemberUpdateNoti = (Nettention.Proud.RmiID)18039;
			public const Nettention.Proud.RmiID PartySuggestionPlayersRes = (Nettention.Proud.RmiID)18040;
			public const Nettention.Proud.RmiID PartyEnterDungeonCanceledRes = (Nettention.Proud.RmiID)18042;
			public const Nettention.Proud.RmiID PetCollectInfoV2Res = (Nettention.Proud.RmiID)19009;
			public const Nettention.Proud.RmiID PetEquipOffV2Noti = (Nettention.Proud.RmiID)19010;
			public const Nettention.Proud.RmiID PetEquipOffV2Res = (Nettention.Proud.RmiID)19011;
			public const Nettention.Proud.RmiID PetEquipV2Noti = (Nettention.Proud.RmiID)19012;
			public const Nettention.Proud.RmiID PetEquipV2Res = (Nettention.Proud.RmiID)19013;
			public const Nettention.Proud.RmiID PetFeedUseV2Res = (Nettention.Proud.RmiID)19014;
			public const Nettention.Proud.RmiID PetGachaV2Res = (Nettention.Proud.RmiID)19015;
			public const Nettention.Proud.RmiID PetInfoV2Res = (Nettention.Proud.RmiID)19016;
			public const Nettention.Proud.RmiID PetMixV2Res = (Nettention.Proud.RmiID)19017;
			public const Nettention.Proud.RmiID PetUpgradeV2Res = (Nettention.Proud.RmiID)19018;
			public const Nettention.Proud.RmiID PetInActiveBuffRes = (Nettention.Proud.RmiID)19020;
			public const Nettention.Proud.RmiID PhaseFieldEndV2Res = (Nettention.Proud.RmiID)20003;
			public const Nettention.Proud.RmiID PhaseFieldStartV2Res = (Nettention.Proud.RmiID)20004;
			public const Nettention.Proud.RmiID PlayerCrimeV2Noti = (Nettention.Proud.RmiID)21013;
			public const Nettention.Proud.RmiID PlayerDeleteRes = (Nettention.Proud.RmiID)21014;
			public const Nettention.Proud.RmiID PlayerEventV2Noti = (Nettention.Proud.RmiID)21015;
			public const Nettention.Proud.RmiID PlayerExpChangeV2Noti = (Nettention.Proud.RmiID)21016;
			public const Nettention.Proud.RmiID PlayerGetMacroRes = (Nettention.Proud.RmiID)21017;
			public const Nettention.Proud.RmiID PlayerLootingV2Noti = (Nettention.Proud.RmiID)21018;
			public const Nettention.Proud.RmiID PlayerMapMoveV2Res = (Nettention.Proud.RmiID)21019;
			public const Nettention.Proud.RmiID PlayerMoveV2Noti = (Nettention.Proud.RmiID)21020;
			public const Nettention.Proud.RmiID PlayerMoveV2Res = (Nettention.Proud.RmiID)21021;
			public const Nettention.Proud.RmiID PlayerTendencyNoti = (Nettention.Proud.RmiID)21022;
			public const Nettention.Proud.RmiID PlayerPvpValueNoti = (Nettention.Proud.RmiID)21023;
			public const Nettention.Proud.RmiID PlayerResurrectionV2Noti = (Nettention.Proud.RmiID)21024;
			public const Nettention.Proud.RmiID PlayerResurrectionV2Res = (Nettention.Proud.RmiID)21025;
			public const Nettention.Proud.RmiID PlayerSetMacroRes = (Nettention.Proud.RmiID)21026;
			public const Nettention.Proud.RmiID PlayerStatChangeV2Noti = (Nettention.Proud.RmiID)21027;
			public const Nettention.Proud.RmiID PlayerStatPointChangeV2Noti = (Nettention.Proud.RmiID)21028;
			public const Nettention.Proud.RmiID PlayerStatPointChangeV2Res = (Nettention.Proud.RmiID)21029;
			public const Nettention.Proud.RmiID PlayerStatPointInitV2Res = (Nettention.Proud.RmiID)21030;
			public const Nettention.Proud.RmiID PlayerStatV2Res = (Nettention.Proud.RmiID)21031;
			public const Nettention.Proud.RmiID PlayerWalletUpdateV2Noti = (Nettention.Proud.RmiID)21032;
			public const Nettention.Proud.RmiID PlayerWalletV2Noti = (Nettention.Proud.RmiID)21033;
			public const Nettention.Proud.RmiID PlayerWantedV2Noti = (Nettention.Proud.RmiID)21034;
			public const Nettention.Proud.RmiID PlayerDeathInfoRes = (Nettention.Proud.RmiID)21036;
			public const Nettention.Proud.RmiID RecoverPlayerExpRes = (Nettention.Proud.RmiID)21038;
			public const Nettention.Proud.RmiID PlayerCombatCapabilityNoti = (Nettention.Proud.RmiID)21039;
			public const Nettention.Proud.RmiID PlayerClassUpV2Res = (Nettention.Proud.RmiID)21041;
			public const Nettention.Proud.RmiID QuickslotSetRes = (Nettention.Proud.RmiID)21043;
			public const Nettention.Proud.RmiID QuickslotListNoti = (Nettention.Proud.RmiID)21044;
			public const Nettention.Proud.RmiID MembershipAddNoti = (Nettention.Proud.RmiID)21045;
			public const Nettention.Proud.RmiID MembershipUpdateNoti = (Nettention.Proud.RmiID)21046;
			public const Nettention.Proud.RmiID MembershipListNoti = (Nettention.Proud.RmiID)21047;
			public const Nettention.Proud.RmiID PlayerExpRecoveryPopupRes = (Nettention.Proud.RmiID)21049;
			public const Nettention.Proud.RmiID RTTPlayerMoveV2Res = (Nettention.Proud.RmiID)21051;
			public const Nettention.Proud.RmiID CheatGetQuestV2Noti = (Nettention.Proud.RmiID)22012;
			public const Nettention.Proud.RmiID DailyQuestOpenV2Noti = (Nettention.Proud.RmiID)22013;
			public const Nettention.Proud.RmiID PlayerQuestProgressV2Noti = (Nettention.Proud.RmiID)22014;
			public const Nettention.Proud.RmiID QuestAbandonV2Res = (Nettention.Proud.RmiID)22015;
			public const Nettention.Proud.RmiID QuestAcceptV2Res = (Nettention.Proud.RmiID)22016;
			public const Nettention.Proud.RmiID QuestCompleteV2Res = (Nettention.Proud.RmiID)22017;
			public const Nettention.Proud.RmiID QuestConditionCompleteV2Res = (Nettention.Proud.RmiID)22018;
			public const Nettention.Proud.RmiID QuestListV2Res = (Nettention.Proud.RmiID)22019;
			public const Nettention.Proud.RmiID QuestPortalV2Res = (Nettention.Proud.RmiID)22020;
			public const Nettention.Proud.RmiID QuestRegisterV2Res = (Nettention.Proud.RmiID)22021;
			public const Nettention.Proud.RmiID QuestRerollV2Res = (Nettention.Proud.RmiID)22022;
			public const Nettention.Proud.RmiID QuestResetCheatV2Noti = (Nettention.Proud.RmiID)22023;
			public const Nettention.Proud.RmiID QuestRewardV2Res = (Nettention.Proud.RmiID)22024;
			public const Nettention.Proud.RmiID QuestTalkCompleteV2Res = (Nettention.Proud.RmiID)22025;
			public const Nettention.Proud.RmiID ResetDailyQuestV2Noti = (Nettention.Proud.RmiID)22026;
			public const Nettention.Proud.RmiID TutorialSkipV2Res = (Nettention.Proud.RmiID)22027;
			public const Nettention.Proud.RmiID GuildRelationRes = (Nettention.Proud.RmiID)23003;
			public const Nettention.Proud.RmiID PlayerRelationRes = (Nettention.Proud.RmiID)23004;
			public const Nettention.Proud.RmiID RelationsNoti = (Nettention.Proud.RmiID)23005;
			public const Nettention.Proud.RmiID RideAttachDeleteV2Res = (Nettention.Proud.RmiID)24013;
			public const Nettention.Proud.RmiID RideAttachDisassembleV2Res = (Nettention.Proud.RmiID)24014;
			public const Nettention.Proud.RmiID RideAttachEquipOffV2Noti = (Nettention.Proud.RmiID)24015;
			public const Nettention.Proud.RmiID RideAttachEquipOffV2Res = (Nettention.Proud.RmiID)24016;
			public const Nettention.Proud.RmiID RideAttachEquipV2Noti = (Nettention.Proud.RmiID)24017;
			public const Nettention.Proud.RmiID RideAttachEquipV2Res = (Nettention.Proud.RmiID)24018;
			public const Nettention.Proud.RmiID RideAttachGachaV2Res = (Nettention.Proud.RmiID)24019;
			public const Nettention.Proud.RmiID RideAttachInvenExtendV2Res = (Nettention.Proud.RmiID)24020;
			public const Nettention.Proud.RmiID RideCollectInfosNoti = (Nettention.Proud.RmiID)24021;
			public const Nettention.Proud.RmiID RideEquipOffV2Res = (Nettention.Proud.RmiID)24022;
			public const Nettention.Proud.RmiID RideEquipV2Res = (Nettention.Proud.RmiID)24023;
			public const Nettention.Proud.RmiID RideGachaV2Res = (Nettention.Proud.RmiID)24024;
			public const Nettention.Proud.RmiID RideInfosNoti = (Nettention.Proud.RmiID)24025;
			public const Nettention.Proud.RmiID RideMixV2Res = (Nettention.Proud.RmiID)24026;
			public const Nettention.Proud.RmiID RideSitOffV2Noti = (Nettention.Proud.RmiID)24027;
			public const Nettention.Proud.RmiID RideSitOffV2Res = (Nettention.Proud.RmiID)24028;
			public const Nettention.Proud.RmiID RideSitV2Noti = (Nettention.Proud.RmiID)24029;
			public const Nettention.Proud.RmiID RideSitV2Res = (Nettention.Proud.RmiID)24030;
			public const Nettention.Proud.RmiID BuyCashShopItemV2Res = (Nettention.Proud.RmiID)25004;
			public const Nettention.Proud.RmiID BuyGameShopItemV2Res = (Nettention.Proud.RmiID)25005;
			public const Nettention.Proud.RmiID GameShopSellItemV2Res = (Nettention.Proud.RmiID)25006;
			public const Nettention.Proud.RmiID ShopBuyCountListNoti = (Nettention.Proud.RmiID)25007;
			public const Nettention.Proud.RmiID ChangedSiegeWarMatchInfoV2Noti = (Nettention.Proud.RmiID)26005;
			public const Nettention.Proud.RmiID ChangeSiegeModeV2Res = (Nettention.Proud.RmiID)26006;
			public const Nettention.Proud.RmiID ChangeSiegeWarInfoV2Noti = (Nettention.Proud.RmiID)26007;
			public const Nettention.Proud.RmiID ChangeSiegeWarObjectInfoV2Noti = (Nettention.Proud.RmiID)26008;
			public const Nettention.Proud.RmiID ChoiceSiegeWarFactionV2Res = (Nettention.Proud.RmiID)26009;
			public const Nettention.Proud.RmiID CreatedDungeonSiegeWarV2Noti = (Nettention.Proud.RmiID)26010;
			public const Nettention.Proud.RmiID DungeonSiegeWarClearV2Noti = (Nettention.Proud.RmiID)26011;
			public const Nettention.Proud.RmiID GetSiegeWarInfoV2Res = (Nettention.Proud.RmiID)26012;
			public const Nettention.Proud.RmiID GetSiegeWarMatchInfoV2Res = (Nettention.Proud.RmiID)26013;
			public const Nettention.Proud.RmiID ShowLocalizationV2Noti = (Nettention.Proud.RmiID)26014;
			public const Nettention.Proud.RmiID ActorChangeBattleModeV2Noti = (Nettention.Proud.RmiID)27012;
			public const Nettention.Proud.RmiID BuffListInfoV2Res = (Nettention.Proud.RmiID)27013;
			public const Nettention.Proud.RmiID SkillChangeAutoUseV2Res = (Nettention.Proud.RmiID)27014;
			public const Nettention.Proud.RmiID SkillChangePresetV2Res = (Nettention.Proud.RmiID)27015;
			public const Nettention.Proud.RmiID SkillDotEffectV2Noti = (Nettention.Proud.RmiID)27016;
			public const Nettention.Proud.RmiID SkillEquipV2Res = (Nettention.Proud.RmiID)27017;
			public const Nettention.Proud.RmiID SkillHitEffectV2Noti = (Nettention.Proud.RmiID)27018;
			public const Nettention.Proud.RmiID SkillHitV2Noti = (Nettention.Proud.RmiID)27019;
			public const Nettention.Proud.RmiID SkillHitV2Res = (Nettention.Proud.RmiID)27020;
			public const Nettention.Proud.RmiID SkillLearnV2Res = (Nettention.Proud.RmiID)27021;
			public const Nettention.Proud.RmiID SkillLevelUpV2Res = (Nettention.Proud.RmiID)27022;
			public const Nettention.Proud.RmiID SkillListInfoV2Res = (Nettention.Proud.RmiID)27023;
			public const Nettention.Proud.RmiID SkillPreActionEndV2Noti = (Nettention.Proud.RmiID)27024;
			public const Nettention.Proud.RmiID SkillPresetInfosNoti = (Nettention.Proud.RmiID)27025;
			public const Nettention.Proud.RmiID SkillUnEquipV2Res = (Nettention.Proud.RmiID)27026;
			public const Nettention.Proud.RmiID SkillUpgradeV2Res = (Nettention.Proud.RmiID)27027;
			public const Nettention.Proud.RmiID SkillUseV2Noti = (Nettention.Proud.RmiID)27028;
			public const Nettention.Proud.RmiID SkillUseV2Res = (Nettention.Proud.RmiID)27029;
			public const Nettention.Proud.RmiID SkillDotHealEffectV2Noti = (Nettention.Proud.RmiID)27030;
			public const Nettention.Proud.RmiID RTTSkillUseV2Res = (Nettention.Proud.RmiID)27032;
			public const Nettention.Proud.RmiID RTTSkillHitV2Res = (Nettention.Proud.RmiID)27034;
			public const Nettention.Proud.RmiID TitleAddV2Noti = (Nettention.Proud.RmiID)28004;
			public const Nettention.Proud.RmiID TitleChangeV2Noti = (Nettention.Proud.RmiID)28005;
			public const Nettention.Proud.RmiID TitleChangeV2Res = (Nettention.Proud.RmiID)28006;
			public const Nettention.Proud.RmiID TitleConditionUpdateV2Noti = (Nettention.Proud.RmiID)28007;
			public const Nettention.Proud.RmiID TitleListV2Res = (Nettention.Proud.RmiID)28008;
			public const Nettention.Proud.RmiID TradeCronAverageBalanceRes = (Nettention.Proud.RmiID)29009;
			public const Nettention.Proud.RmiID TradeCronBalanceRes = (Nettention.Proud.RmiID)29010;
			public const Nettention.Proud.RmiID TradeCronBuyRes = (Nettention.Proud.RmiID)29011;
			public const Nettention.Proud.RmiID TradeCronInfoRes = (Nettention.Proud.RmiID)29012;
			public const Nettention.Proud.RmiID TradeCronListRes = (Nettention.Proud.RmiID)29013;
			public const Nettention.Proud.RmiID TradeCronPreviousDayBalanceRes = (Nettention.Proud.RmiID)29014;
			public const Nettention.Proud.RmiID TradeCronSellRes = (Nettention.Proud.RmiID)29015;
			public const Nettention.Proud.RmiID TradeCronWeeklyBalanceRes = (Nettention.Proud.RmiID)29016;
			public const Nettention.Proud.RmiID TradePersonalListNoti = (Nettention.Proud.RmiID)29017;
			public const Nettention.Proud.RmiID TradePersonalRequestRes = (Nettention.Proud.RmiID)29019;
			public const Nettention.Proud.RmiID TradePersonalUpdateNoti = (Nettention.Proud.RmiID)29020;
			public const Nettention.Proud.RmiID TradePersonalAddNoti = (Nettention.Proud.RmiID)29021;
			public const Nettention.Proud.RmiID TradePersonalDeleteNoti = (Nettention.Proud.RmiID)29022;
			public const Nettention.Proud.RmiID TradePersonalAcceptRes = (Nettention.Proud.RmiID)29024;
			public const Nettention.Proud.RmiID TradePersonalRefuseRes = (Nettention.Proud.RmiID)29026;
			public const Nettention.Proud.RmiID TradePersonalCancelRes = (Nettention.Proud.RmiID)29028;
			public const Nettention.Proud.RmiID TradePersonalWithdrawRes = (Nettention.Proud.RmiID)29030;
			public const Nettention.Proud.RmiID TradePersonalFinishRes = (Nettention.Proud.RmiID)29032;
			public const Nettention.Proud.RmiID TradePersonalHistoryRes = (Nettention.Proud.RmiID)29034;
			public const Nettention.Proud.RmiID TradeCronMyListRes = (Nettention.Proud.RmiID)29036;
			public const Nettention.Proud.RmiID TradeCronSettleRes = (Nettention.Proud.RmiID)29038;
			public const Nettention.Proud.RmiID TradeCronTradesRes = (Nettention.Proud.RmiID)29040;
			public const Nettention.Proud.RmiID TradeCronTimeToNextChangeBalanceRes = (Nettention.Proud.RmiID)29042;
			public const Nettention.Proud.RmiID TradeCronCancelRes = (Nettention.Proud.RmiID)29044;
			public const Nettention.Proud.RmiID TradeCronReclaimExpiredRes = (Nettention.Proud.RmiID)29046;
			public const Nettention.Proud.RmiID TradeCronRemainingCanceledPenaltyTimeRes = (Nettention.Proud.RmiID)29048;
			public const Nettention.Proud.RmiID TradeItemSellListNoti = (Nettention.Proud.RmiID)29049;
			public const Nettention.Proud.RmiID TradeItemUpdateNoti = (Nettention.Proud.RmiID)29050;
			public const Nettention.Proud.RmiID TradeItemDeleteNoti = (Nettention.Proud.RmiID)29051;
			public const Nettention.Proud.RmiID TradeItemRegistRes = (Nettention.Proud.RmiID)29053;
			public const Nettention.Proud.RmiID TradeItemCancelRes = (Nettention.Proud.RmiID)29055;
			public const Nettention.Proud.RmiID TradeItemBuyRes = (Nettention.Proud.RmiID)29057;
			public const Nettention.Proud.RmiID TradeItemWithdrawRes = (Nettention.Proud.RmiID)29059;
			public const Nettention.Proud.RmiID TradeItemFinishRes = (Nettention.Proud.RmiID)29061;
			public const Nettention.Proud.RmiID TradeItemHistoryRes = (Nettention.Proud.RmiID)29063;
			public const Nettention.Proud.RmiID TradeItemSearchCategoryRes = (Nettention.Proud.RmiID)29065;
			public const Nettention.Proud.RmiID TradeItemSearchItemIndexRes = (Nettention.Proud.RmiID)29067;
			public const Nettention.Proud.RmiID TradeItemSearchListNoti = (Nettention.Proud.RmiID)29068;
			public const Nettention.Proud.RmiID TradeItemBookmarkAddRes = (Nettention.Proud.RmiID)29070;
			public const Nettention.Proud.RmiID TradeItemBookmarkDeleteRes = (Nettention.Proud.RmiID)29072;
			public const Nettention.Proud.RmiID TradeItemBookmarkListNoti = (Nettention.Proud.RmiID)29073;
			public const Nettention.Proud.RmiID WeaponAppearanceCollectListV2Noti = (Nettention.Proud.RmiID)30007;
			public const Nettention.Proud.RmiID WeaponAppearanceCollectListV2Res = (Nettention.Proud.RmiID)30008;
			public const Nettention.Proud.RmiID WeaponAppearanceEquipV2Noti = (Nettention.Proud.RmiID)30009;
			public const Nettention.Proud.RmiID WeaponAppearanceEquipV2Res = (Nettention.Proud.RmiID)30010;
			public const Nettention.Proud.RmiID WeaponAppearanceExtractFromItemV2Res = (Nettention.Proud.RmiID)30011;
			public const Nettention.Proud.RmiID WeaponAppearanceGachaV2Res = (Nettention.Proud.RmiID)30012;
			public const Nettention.Proud.RmiID WeaponAppearanceHiddenV2Noti = (Nettention.Proud.RmiID)30013;
			public const Nettention.Proud.RmiID WeaponAppearanceHiddenV2Res = (Nettention.Proud.RmiID)30014;
			public const Nettention.Proud.RmiID WeaponAppearanceListV2Noti = (Nettention.Proud.RmiID)30015;
			public const Nettention.Proud.RmiID WeaponAppearanceListV2Res = (Nettention.Proud.RmiID)30016;
			public const Nettention.Proud.RmiID WeaponAppearanceUnequipV2Noti = (Nettention.Proud.RmiID)30017;
			public const Nettention.Proud.RmiID WeaponAppearanceUnequipV2Res = (Nettention.Proud.RmiID)30018;
			public const Nettention.Proud.RmiID AccountCreateNameRes = (Nettention.Proud.RmiID)40002;
			public const Nettention.Proud.RmiID ZoneStatusRes = (Nettention.Proud.RmiID)41002;
			public const Nettention.Proud.RmiID ZoneStatusNoti = (Nettention.Proud.RmiID)41003;
			public const Nettention.Proud.RmiID BloodFogEnterRes = (Nettention.Proud.RmiID)42002;
			public const Nettention.Proud.RmiID BloodFogLeaveRes = (Nettention.Proud.RmiID)42004;
			public const Nettention.Proud.RmiID BloodFogUseBuffRes = (Nettention.Proud.RmiID)42006;
			public const Nettention.Proud.RmiID BloodFogChangeWaveNoti = (Nettention.Proud.RmiID)42007;
			public const Nettention.Proud.RmiID BloodFogEventNoti = (Nettention.Proud.RmiID)42008;
			public const Nettention.Proud.RmiID BloodFogKickoutNoti = (Nettention.Proud.RmiID)42009;
			public const Nettention.Proud.RmiID BloodFogPlayerDeathNoti = (Nettention.Proud.RmiID)42010;
			public const Nettention.Proud.RmiID BloodFogPlayerPointUpdateNoti = (Nettention.Proud.RmiID)42011;
			public const Nettention.Proud.RmiID BloodFogPlayerRankUpdateNoti = (Nettention.Proud.RmiID)42012;
			public const Nettention.Proud.RmiID BloodFogResultNoti = (Nettention.Proud.RmiID)42013;
			public const Nettention.Proud.RmiID S2CRttRes = (Nettention.Proud.RmiID)50002;
			public const Nettention.Proud.RmiID S2CRttReq = (Nettention.Proud.RmiID)50003;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			PlayerSelectRes,
			PlayerEnterStageFirstRes,
			PlayerEnterStageSecondRes,
			PlayerEnterStageThirdRes,
			PlayerEnterStageFourthRes,
			PlayerEnterStageFifthRes,
			PlayerGameEnterRes,
			AuthenticateBotCredentialRes,
			ActorAddBuffV2Noti,
			ActorChangedLevelToMeV2Noti,
			ActorChangedLevelV2Noti,
			ActorChangeStateV2Noti,
			ActorCostumeNoti,
			ActorDeathV2Noti,
			ActorDisAppearV2Noti,
			ActorGuildV2Noti,
			ActorHpMpUpdateV2Noti,
			ActorHpUpdateV2Noti,
			ActorMoveV2Noti,
			ActorMpUpdateV2Noti,
			ActorPetV2Noti,
			ActorRemoveBuffV2Noti,
			ActorRideV2Noti,
			ActorsDisAppearV2Noti,
			MonsterActorAppearV2Noti,
			MonsterActorsAppearV2Noti,
			MonsterActorTargetNoti,
			PlayerActorAppearV2Noti,
			PlayerActorsAppearV2Noti,
			PlayerActorZoneStateNoti,
			ActorStatSyncNoti,
			PropActorAppearNoti,
			ActorPendingDisAppearNoti,
			PropActorsAppearNoti,
			DesignateBindStoneRes,
			PortalByBindStoneRes,
			PlayerBlackRosterGetPreferenceRes,
			PlayerBlackRosterObservingNoti,
			PlayerBlackRosterObservingRes,
			PlayerBlackRosterProvocationNoti,
			PlayerBlackRosterProvocationRes,
			PlayerBlackRosterRankRes,
			PlayerBlackRosterRevengeRes,
			PlayerBlackRosterSetPreferenceRes,
			PlayerBlackRostersRes,
			PlayerBlackRosterLastWeekRankRes,
			PlayerBlackRosterMessageNoti,
			CheatGetMainQuestV2Noti,
			CheatMessageV2Res,
			CheatQuestResetV2Noti,
			AccountBlockPlayerAddRes,
			AccountBlockPlayerDeleteRes,
			AccountBlockPlayerReasonEditRes,
			AccountBlockPlayersRes,
			ChatMessageV2Noti,
			ChatMessageV2Res,
			PlayerSearchV2Res,
			LinkItemInfoRes,
			CostumeCardBuildRes,
			CostumeCardGachaRes,
			CostumeCardInfoRes,
			CostumeCardMixRes,
			CostumeCollectNoti,
			CostumeCollectRes,
			CostumeEquipBodyRes,
			CostumeEquipBodyShowRes,
			CostumeEquipHeadRes,
			CostumeEquipHeadShowRes,
			CostumeInfoRes,
			CostumeConfirmAcceptRes,
			CostumeConfirmChangeRes,
			CostumeConfirmInfoRes,
			PortalEffectNoti,
			PortalEffectRes,
			AttainmentDailyRewardV2Res,
			AttainmentNormalRewardV2Res,
			AttainmentProgressV2Noti,
			AttainmentsNoti,
			AttendanceRewardV2Res,
			BossScheduleNoti,
			BossScheduleRes,
			EventAttendanceListV2Noti,
			EventExchangeRewardV2Res,
			GuildAdminBuffActiveRes,
			GuildAdminBuffBuyRes,
			GuildAdminInfoRes,
			GuildAdminMasterChangeNoti,
			GuildAdminMasterChangeRes,
			GuildAdminMemberBanishNoti,
			GuildAdminMemberBanishRes,
			GuildAdminMemberUpdateNoti,
			GuildAdminMemberUpdateRes,
			GuildAdminUpdateBaseNoti,
			GuildAdminUpdateBaseRes,
			GuildAdminUpdateIntroNoti,
			GuildAdminUpdateIntroRes,
			GuildAdminUpdateNoticeNoti,
			GuildAdminUpdateNoticeRes,
			GuildAdminUpdateTendencyNoti,
			GuildAdminUpdateTendencyRes,
			GuildAdminUpdateTypeNoti,
			GuildAdminUpdateTypeRes,
			GuildAttendRes,
			GuildBaseNoti,
			GuildBuffInfoRes,
			GuildBuffNoti,
			GuildCreateRes,
			GuildDeleteRes,
			GuildDonateRes,
			GuildDonationByCronV2Res,
			GuildFindRes,
			GuildHistoryNoti,
			GuildHistoryRes,
			GuildInfoCallRes,
			GuildInfoRes,
			GuildJoinRequestConfirmNoti,
			GuildJoinRequestConfirmRes,
			GuildJoinRequestListRes,
			GuildLeaveNoti,
			GuildLeaveRes,
			GuildLiveInviteConfirmNoti,
			GuildLiveInviteConfirmRes,
			GuildLiveInviteNoti,
			GuildLiveInviteRes,
			GuildMemberInfoRes,
			GuildMemberNoti,
			GuildMemberStateV2Noti,
			GuildMemberUpdateNoti,
			GuildPointNoti,
			GuildSignRequestCancelRes,
			GuildSignRequestListRes,
			GuildSignRequestRes,
			GuildUpdateCrestNoti,
			GuildUpdateCurrencyV2Noti,
			GuildVoteInfoRes,
			GuildVoteMasterImpeachRes,
			GuildVoteNoti,
			GuildVoteRes,
			GuildWarehouseChangeSizeV2Res,
			GuildWarehouseInfoV2Res,
			GuildWarehouseItemMoveV2Res,
			GuildWarehouseWalletMoveV2Res,
			GuildRubyNoti,
			GuildCronNoti,
			GuildTerritoryInfoRes,
			GuildTerritorySetRes,
			WorldTerritoryOverviewRes,
			WorldBossLastAttackNoti,
			DungeonClearHistoryV2Noti,
			DungeonClearV2Noti,
			DungeonCronUpdateV2Noti,
			DungeonEnterV2Res,
			DungeonExpUpdateV2Noti,
			DungeonGiveUpV2Res,
			DungeonLeaveV2Res,
			DungeonLoadingCompleteAllV2Noti,
			DungeonLoadingCompleteV2Res,
			ExpDungeonClearNoti,
			EquipDungeonClearNoti,
			MineralDungeonClearNoti,
			PartyDungeonClearNoti,
			InteractStartRes,
			InteractEndRes,
			InteractCancelRes,
			InteractNoti,
			EquipmentVisibleV2Res,
			InventoryChangeSizeV2Res,
			ItemAddOptionV2Res,
			ItemAddV2Noti,
			ItemChangeOptionV2Res,
			ItemCollectionBookmarksRegisterV2Res,
			ItemCollectionBookmarksUnregisterV2Res,
			ItemCollectionListV2Noti,
			ItemCollectionRegisterV2Res,
			ItemCombineV2Res,
			ItemDeleteV2Noti,
			ItemDeleteV2Res,
			ItemDisassembleV2Res,
			ItemEnchantV2Res,
			ItemEquipV2Noti,
			ItemEquipV2Res,
			ItemIntensionV2Res,
			ItemMixOptionV2Res,
			ItemPackageUseV2Res,
			ItemProductionV2Res,
			ItemSelectUseV2Res,
			ItemUpdateV2Noti,
			ItemUpgradeV2Res,
			ItemUseV2Res,
			PkLootingAddV2Noti,
			PkLootingItemV2Res,
			PkLootingListV2Res,
			PkLootingV2Noti,
			PlayerInventoryExtendInfoNoti,
			PlayerInventoryInfoV2Noti,
			WarehouseChangeSizeV2Res,
			WarehouseInfoV2Res,
			WarehouseItemMoveV2Res,
			ItemIntentionSucceedNoti,
			ItemSetLockRes,
			ItemMarketPriceRes,
			ItemInheritRes,
			MailListV2Res,
			MailReadAllV2Res,
			MailReadV2Res,
			MatchingApplyRes,
			MatchingCancelRes,
			MatchingCompleteNoti,
			MatchingIncompleteNoti,
			MatchingMatchedNoti,
			MatchingRejectReplyNoti,
			MatchingReplyNoti,
			MatchingReplyRes,
			AuthenticatePlayerCredentialRes,
			BindStonesNoti,
			BroadCastContextNoti,
			BroadCastContextRes,
			CutSceneEndV2Res,
			CutSceneStartV2Res,
			CutSceneStateV2Noti,
			DebugPlayerStateV2Noti,
			LogOutRes,
			PortalV2Res,
			ReturnToLobbyRes,
			ServerTimeV2Res,
			SystemMessageV2Noti,
			TemporalFluxZoneEnterNoti,
			TemporalFluxZoneExitNoti,
			TestPacketV2Noti,
			TestPacketV2Res,
			TicketInfoV2Noti,
			TriggerActivateMapMoveV2Noti,
			TriggerActivateV2Res,
			UnionV2Res,
			ZoneLoadingCompletedRes,
			BossDamagedInfoNoti,
			BossFirstDamagedNoti,
			BossKilledNoti,
			BossKilledRewardNoti,
			GainMessageNoti,
			TicketUpdateNoti,
			BossDamagedInfoRes,
			WorldBossDamagedInfoNoti,
			BossTakenDamageOnPlayerKillNoti,
			PartyChangeLootingNoti,
			PartyChangeLootingRes,
			PartyCreateRes,
			PartyDisbandNoti,
			PartyDisbandRes,
			PartyDungeonEntranceInquiryRes,
			PartyEnterDungeonCanceledNoti,
			PartyEnterDungeonNoti,
			PartyEnterDungeonReplyNoti,
			PartyEnterDungeonReplyRes,
			PartyEnterDungeonRes,
			PartyEnterNoti,
			PartyInfoNoti,
			PartyInfoRes,
			PartyInviteNoti,
			PartyInviteReplyNoti,
			PartyInviteReplyRes,
			PartyInviteRes,
			PartyKickedNoti,
			PartyLeaderChangeNoti,
			PartyLeaderChangeRes,
			PartyLeaveNoti,
			PartyLeaveRes,
			PartyMemberKickNoti,
			PartyMemberKickRes,
			PartyMemberUpdateNoti,
			PartySuggestionPlayersRes,
			PartyEnterDungeonCanceledRes,
			PetCollectInfoV2Res,
			PetEquipOffV2Noti,
			PetEquipOffV2Res,
			PetEquipV2Noti,
			PetEquipV2Res,
			PetFeedUseV2Res,
			PetGachaV2Res,
			PetInfoV2Res,
			PetMixV2Res,
			PetUpgradeV2Res,
			PetInActiveBuffRes,
			PhaseFieldEndV2Res,
			PhaseFieldStartV2Res,
			PlayerCrimeV2Noti,
			PlayerDeleteRes,
			PlayerEventV2Noti,
			PlayerExpChangeV2Noti,
			PlayerGetMacroRes,
			PlayerLootingV2Noti,
			PlayerMapMoveV2Res,
			PlayerMoveV2Noti,
			PlayerMoveV2Res,
			PlayerTendencyNoti,
			PlayerPvpValueNoti,
			PlayerResurrectionV2Noti,
			PlayerResurrectionV2Res,
			PlayerSetMacroRes,
			PlayerStatChangeV2Noti,
			PlayerStatPointChangeV2Noti,
			PlayerStatPointChangeV2Res,
			PlayerStatPointInitV2Res,
			PlayerStatV2Res,
			PlayerWalletUpdateV2Noti,
			PlayerWalletV2Noti,
			PlayerWantedV2Noti,
			PlayerDeathInfoRes,
			RecoverPlayerExpRes,
			PlayerCombatCapabilityNoti,
			PlayerClassUpV2Res,
			QuickslotSetRes,
			QuickslotListNoti,
			MembershipAddNoti,
			MembershipUpdateNoti,
			MembershipListNoti,
			PlayerExpRecoveryPopupRes,
			RTTPlayerMoveV2Res,
			CheatGetQuestV2Noti,
			DailyQuestOpenV2Noti,
			PlayerQuestProgressV2Noti,
			QuestAbandonV2Res,
			QuestAcceptV2Res,
			QuestCompleteV2Res,
			QuestConditionCompleteV2Res,
			QuestListV2Res,
			QuestPortalV2Res,
			QuestRegisterV2Res,
			QuestRerollV2Res,
			QuestResetCheatV2Noti,
			QuestRewardV2Res,
			QuestTalkCompleteV2Res,
			ResetDailyQuestV2Noti,
			TutorialSkipV2Res,
			GuildRelationRes,
			PlayerRelationRes,
			RelationsNoti,
			RideAttachDeleteV2Res,
			RideAttachDisassembleV2Res,
			RideAttachEquipOffV2Noti,
			RideAttachEquipOffV2Res,
			RideAttachEquipV2Noti,
			RideAttachEquipV2Res,
			RideAttachGachaV2Res,
			RideAttachInvenExtendV2Res,
			RideCollectInfosNoti,
			RideEquipOffV2Res,
			RideEquipV2Res,
			RideGachaV2Res,
			RideInfosNoti,
			RideMixV2Res,
			RideSitOffV2Noti,
			RideSitOffV2Res,
			RideSitV2Noti,
			RideSitV2Res,
			BuyCashShopItemV2Res,
			BuyGameShopItemV2Res,
			GameShopSellItemV2Res,
			ShopBuyCountListNoti,
			ChangedSiegeWarMatchInfoV2Noti,
			ChangeSiegeModeV2Res,
			ChangeSiegeWarInfoV2Noti,
			ChangeSiegeWarObjectInfoV2Noti,
			ChoiceSiegeWarFactionV2Res,
			CreatedDungeonSiegeWarV2Noti,
			DungeonSiegeWarClearV2Noti,
			GetSiegeWarInfoV2Res,
			GetSiegeWarMatchInfoV2Res,
			ShowLocalizationV2Noti,
			ActorChangeBattleModeV2Noti,
			BuffListInfoV2Res,
			SkillChangeAutoUseV2Res,
			SkillChangePresetV2Res,
			SkillDotEffectV2Noti,
			SkillEquipV2Res,
			SkillHitEffectV2Noti,
			SkillHitV2Noti,
			SkillHitV2Res,
			SkillLearnV2Res,
			SkillLevelUpV2Res,
			SkillListInfoV2Res,
			SkillPreActionEndV2Noti,
			SkillPresetInfosNoti,
			SkillUnEquipV2Res,
			SkillUpgradeV2Res,
			SkillUseV2Noti,
			SkillUseV2Res,
			SkillDotHealEffectV2Noti,
			RTTSkillUseV2Res,
			RTTSkillHitV2Res,
			TitleAddV2Noti,
			TitleChangeV2Noti,
			TitleChangeV2Res,
			TitleConditionUpdateV2Noti,
			TitleListV2Res,
			TradeCronAverageBalanceRes,
			TradeCronBalanceRes,
			TradeCronBuyRes,
			TradeCronInfoRes,
			TradeCronListRes,
			TradeCronPreviousDayBalanceRes,
			TradeCronSellRes,
			TradeCronWeeklyBalanceRes,
			TradePersonalListNoti,
			TradePersonalRequestRes,
			TradePersonalUpdateNoti,
			TradePersonalAddNoti,
			TradePersonalDeleteNoti,
			TradePersonalAcceptRes,
			TradePersonalRefuseRes,
			TradePersonalCancelRes,
			TradePersonalWithdrawRes,
			TradePersonalFinishRes,
			TradePersonalHistoryRes,
			TradeCronMyListRes,
			TradeCronSettleRes,
			TradeCronTradesRes,
			TradeCronTimeToNextChangeBalanceRes,
			TradeCronCancelRes,
			TradeCronReclaimExpiredRes,
			TradeCronRemainingCanceledPenaltyTimeRes,
			TradeItemSellListNoti,
			TradeItemUpdateNoti,
			TradeItemDeleteNoti,
			TradeItemRegistRes,
			TradeItemCancelRes,
			TradeItemBuyRes,
			TradeItemWithdrawRes,
			TradeItemFinishRes,
			TradeItemHistoryRes,
			TradeItemSearchCategoryRes,
			TradeItemSearchItemIndexRes,
			TradeItemSearchListNoti,
			TradeItemBookmarkAddRes,
			TradeItemBookmarkDeleteRes,
			TradeItemBookmarkListNoti,
			WeaponAppearanceCollectListV2Noti,
			WeaponAppearanceCollectListV2Res,
			WeaponAppearanceEquipV2Noti,
			WeaponAppearanceEquipV2Res,
			WeaponAppearanceExtractFromItemV2Res,
			WeaponAppearanceGachaV2Res,
			WeaponAppearanceHiddenV2Noti,
			WeaponAppearanceHiddenV2Res,
			WeaponAppearanceListV2Noti,
			WeaponAppearanceListV2Res,
			WeaponAppearanceUnequipV2Noti,
			WeaponAppearanceUnequipV2Res,
			AccountCreateNameRes,
			ZoneStatusRes,
			ZoneStatusNoti,
			BloodFogEnterRes,
			BloodFogLeaveRes,
			BloodFogUseBuffRes,
			BloodFogChangeWaveNoti,
			BloodFogEventNoti,
			BloodFogKickoutNoti,
			BloodFogPlayerDeathNoti,
			BloodFogPlayerPointUpdateNoti,
			BloodFogPlayerRankUpdateNoti,
			BloodFogResultNoti,
			S2CRttRes,
			S2CRttReq,
		};
	}
}






				 
